### ISSUE TITLE
Consider removing querySelector condition and use the fallback insertion point in all browsers

### ISSUE THREAD

**Issue by scottjehl** [filamentgroup/loadCSS#102]
This would mainly mean that the default injection location would be after the last childnode element in either the body, or the head if the body isn't yet defined. We currently inject after the last style/script/link in qsa browsers, but this seems like it may be an unnecessary refinement compared to the fallback.

Lines in question: https://github.com/filamentgroup/loadCSS/blob/master/loadCSS.js#L23-L28

**Comment by scottjehl** [comment]
cc @paulirish

**Comment by paulirish** [comment]
seems cool. basically kill the first `if` branch and always after the last node in the DOM.

seems good!
