### ISSUE TITLE
Delay link insertion (and thus, the request) until either <head> or entire DOM is ready

### ISSUE THREAD

**Issue by scottjehl** [filamentgroup/loadCSS#105]
I think we should consider delaying the `link` append until a time when we can be sure that we're seeing all the scripts and styles in the DOM. 

Currently, loadCSS runs before the DOM is ready, and depending on its location in the DOM, it'll often only see nodes that come before its parent script tag. That's often not a problem, particularly if you place the script tag that contains loadCSS after your other stylesheets. But if you don't, it'll often mean that the new link will be inserted before later stylesheets, possibly messing with cascade.

waiting for domcontentloaded or RAF is probably best. If not that, maybe waiting for document.body would at least be sufficient to get all the links in `head`

**Comment by MarcoHengstenberg** [comment]
Isn't this something related to what a specific project/webiste needs?

I mean, sometimes you would want the stylesheet to be there as soon as possible, whereas in other cases it's just like you're pointing out here.

Imho this should be kept as an option – or it should be possible to opt out. Whatever makes more sense. :smiley:

**Comment by scottjehl** [comment]
@MarcoHengstenberg yeah, that may be the best route if we do it. Thanks
