### ISSUE TITLE
Load in IE lt 8?

### ISSUE THREAD

**Issue by sogen** [filamentgroup/loadCSS#11]
Hi, what's the best way to make it work in IE 7, 6?

Thanks.

**Comment by melnikovkolya** [comment]
Could anyone please tell me why the issue is closed? Is it because the original code of loadCSS has been changed or because there is no way of supporting it in IE versions: 6-8

**Comment by sogen** [comment]
I closed it since it got no answers.
Reopening

**Comment by scottjehl** [comment]
Been a little while since last test but it used to work in IE, with the exception that it may not load _async_ in those versions (at least you get a stylesheet though). Worth getting this tested and documented.

**Comment by scottjehl** [comment]
Tested in IE 6-8 and a CSS file loads at least, though whether or not it loads async may vary on the version and what else is going on in the DOM. Noted here for further study: https://github.com/filamentgroup/loadCSS/issues/64#issuecomment-125633790
