### ISSUE TITLE
ios 9.2 Chrome v47 /  LoadCSS creates the <link> tag before the inline styles

### ISSUE THREAD

**Issue by jonathanlevaillant** [filamentgroup/loadCSS#114]
Hello,

on my iPhone 6 (ios 9.2) with Chrome v47 (It's working on Safari), 
loadCSS moves the link tag before the inline css <style>inline css</style>

So, my inline critical css overloads my full style css ... I saw this bug only on ios 9.2 with Chrome v47

Any ideas ? :)
Thanks in advance,
Jonathan

**Comment by scottjehl** [comment]
I'll take a look. In the meantime, you can always pass an identifier for a particular location in the DOM to ensure it'll insert just before that node. See the before argument here: https://github.com/filamentgroup/loadCSS/blob/master/README.md#optional-arguments

**Comment by scottjehl** [comment]
Can you test the latest script in Master and see if this is still an issue? I made this page to test now in iOS Chrome, and will close it out if the background goes from gray to green.

http://filamentgroup.github.io/loadCSS/test/test.html

**Comment by scottjehl** [comment]
Tested and confirming it works as expected in iOS Chrome. Try the latest in master and you should be good to go!

**Comment by superpoincare** [comment]
I am getting this. I have all your latest files but it seems the link is loaded before inline. 

Possibly it's because the preload syntax 

`onload="this.rel='stylesheet'"`

inserts the stylesheet at the same location?
