### ISSUE TITLE
loadCSS multiple files

### ISSUE THREAD

**Issue by kofifus** [filamentgroup/loadCSS#116]
Feature request - 

A version of loadCSS that accepts am array of CSS files instead of a single one. And then a version of onloadCSS that continues only when all those files finished downloading.

Thanks!

**Comment by scottjehl** [comment]
Thanks for the suggestion. Currently, you can call loadCSS multiple times and files will be referenced in the order they're called (preserving cascade). Passing more than one file is beyond the scope that the project intends, but thank you for the suggestion.

**Comment by superpoincare** [comment]
@scottjehl Isn't this a bonus in your latest version?. If I use your preload code+polyfill, doesn't [this](https://github.com/filamentgroup/loadCSS/blob/master/src/cssrelpreload.js#L19-L24) automatically load all css
