### ISSUE TITLE
cssrelpreload.js bug? 

### ISSUE THREAD

**Issue by dtjones** [filamentgroup/loadCSS#128]
I've looked in the DOMTokenList/relList spec and I can not find any reference to the `supports` method, should this be `contains` ?

**Comment by scottjehl** [comment]
Good question. It's already working in Canary, which supports these apis, for what it's worth.

As for that method vs contains, maybe @yoavweiss would have info...?

**Comment by yoavweiss** [comment]
https://dom.spec.whatwg.org/#dom-domtokenlist-supports is where `supports()` is defined.
`contains("foobar")` will return true if your element's `rel` attribute contains a "foobar" relation.

**Comment by dtjones** [comment]
Yep its in there! I obviously didn't look hard enough, I only found an old [W3C working draft](https://www.w3.org/TR/2011/WD-html5-author-20110705/common-dom-interfaces.html#domtokenlist) which didn't mention it. Thanks for the link.
