### ISSUE TITLE
Fonts on second load on IE11

### ISSUE THREAD

**Issue by vijayaraghavanramanan** [filamentgroup/loadCSS#130]
@scottjehl as highlighted by [you,](https://www.filamentgroup.com/lab/font-events.html) the best way to load fonts in browsers is using loadCSS with woff links instead of data URIs, fontfaceobserver with classes and cookies to set html class to fonts-loaded by default on second load. This approach is like the upcoming `font-display:swap` for old browsers. 

But even if I don't use this, I have observed that on second load, loading fonts using loadCSS used to neither FOUT not FOIT on second load as the css file is in the cache and loadCSS finishes super fast. 

However, in the new changes done a few days ago, the part where the code waits for body to become available - the code specific to IE11. I have observed that because of this, IE11's fonts css with @font-face  links to woff files changes media slightly later. This has the effect of a flash of a FOUT. (more like characters/glyphs jiggling)

Although I haven't tested, I think even if one were to include fontfaceobserver, cookies, classes, the issue won't go away. IE11 is unbelievably fast in start render and might start to render even before the browser sees a @font-face declaration. This is fine on first load but not optimized for second load, as previously. 

I don't have a demo, as I have made changes on my site. Feel free to close the issue but can you please keep this in mind when doing your tests?

**Comment by aFarkas** [comment]
The issue here is actually a little bit bigger. Normal blocking stylesheets do block under normal circumstances the "creation" of `document.body`. Which basically means, if you had the following structure.

```html
<html>
    <head>

</html>

**Comment by vijayaraghavanramanan** [comment]
Hi @aFarkas ,

I was able to solve this issue by modifying Scott's trick here: 

https://github.com/filamentgroup/loadCSS/issues/135#issuecomment-180774393

What I do is, I  run rp.poly 

https://github.com/filamentgroup/loadCSS/blob/master/src/cssrelpreload.js#L30

if sessionStorage.fullcssloaded is false and do document.write if true.

**Comment by aFarkas** [comment]
@vijayaraghavanramanan 
This doesn't solve the underlying problem. Waiting for `document.body` in all browsers means, that there is a long time between calling loadCSS and starting the actual download.

Your workaround only works because you don't use loadCSS in cached situations anymore. If you would check a network waterfall in empty cache situations you will see downloads of async CSS is not only async it is heavily delayed (delayed until normal CSS is fully downloaded).

**Comment by vijayaraghavanramanan** [comment]
@aFarkas 

Maybe that's because when used with the polyfill, the output doesn't have something like loadCSS("http://www.example.com/all.css") and instead gets the link by a loop finding all link tags and this runs only after CSSOM is ready? Without using the code as a polyfill, when we do a loadCSS( ...) directly, the browser starts to download even if JS has not started to run. But now JS running is more important to start the fetch. (?)
