### ISSUE TITLE
Enhance?

### ISSUE THREAD

**Issue by vijayaraghavanramanan** [filamentgroup/loadCSS#135]
It is possible to use to do something like session.storage.loadCSS to true on first load and check if true for second load and immediately set media to media || "all" if session.storage.loadCSS is true, instead of referring to users of your idea to EnhanceJS?

**Comment by scottjehl** [comment]
Yes but I'm not sure we want this script to manipulate storage or cookies itself. 
You could, for example, try something like this in the head of your page:

```
if( localStorage.fullcssloaded ){
document.write( '<link href="..." rel="stylesheet">' );
} else {
loadCSS( "..." );
localStorage.fullcssloaded = "true";
}
```

Still... localStorage lookups are synchronous and measurable in delaying rendering time. It'd be faster to set a cookie or session var and use that in your server templating for logic like shown above. We do that typically and find it works well.

**Comment by vijayaraghavanramanan** [comment]
Thanks Scott. That code is really useful. 

There are some EU cookie laws, so I wanted to keep site cookie free.
