### ISSUE TITLE
Code

### ISSUE THREAD

**Issue by vijayaraghavanramanan** [filamentgroup/loadCSS#136]
May I know what the use of these lines is?

https://github.com/filamentgroup/loadCSS/blob/master/src/cssrelpreload.js#L31-L42

Why isn't it just

`if ( relpreloadsupport() ) {
     //do nothing
} else {
    //loop for href and loadCSS
   ...
}`

**Comment by scottjehl** [comment]
Sure. The polyfill executes very early in page-parsing, often before all links are reachable in the DOM. This part runs the polyfill immediately, but also repeatedly on an interval until the onload event fires.

**Comment by vijayaraghavanramanan** [comment]
I have another question on this. 

Won't the repeated running keep adding the same links because it runs rp.poly a few times and each time some links (such as the first one above the javascript). So while it is discovering links it is also running it for links already being fetched and so insertion is happening multiple times for some?

**Comment by scottjehl** [comment]
@vijayaraghavanramanan this line sets the link's rel to `null` so that it won't be found again.

**Comment by scottjehl** [comment]
Er, sorry this line! :) 
https://github.com/filamentgroup/loadCSS/blob/master/src/cssrelpreload.js#L23

**Comment by vijayaraghavanramanan** [comment]
There's something interesting benefit of that line I observed. Inserting a link before the preload/link is a slightly dangerous thing. So even if one doesn't care for waiting for preload links to be discovered, setting link.rel = null is crucial, else the browser hangs.
