### ISSUE TITLE
npm test fails

### ISSUE THREAD

**Issue by jeremenichelli** [filamentgroup/loadCSS#140]
Hello. I've cloned this repo and tried to add some stuff with their tests and they always failed. Apparently tests are failing even without making any modification.

This is the message:

```sh
Running "qunit:files" (qunit) task
Testing test/qunit/index.html .
>> PhantomJS timed out, possibly due to a missing QUnit start() call.
Warning: 1/1 assertions failed (0ms) Use --force to continue.
```

**Comment by scottjehl** [comment]
fixed in master
