### ISSUE TITLE
rel=stylesheet polyfill matches spec, but Canary no longer likes the spec...

### ISSUE THREAD

**Issue by scottjehl** [filamentgroup/loadCSS#148]
Posting this here until resolved. Hopefully it's a Canary bug. 

loadCSS 1.0 used the `as="style"` attribute, but the spec actually lists it as `as="stylesheet"`. This is fixed in loadCSS 1.1.0 but it now no longer fetches natively in Canary.

@yoavweiss any thoughts?

**Comment by HugoGiraudel** [comment]
On topic, Chrome Version 48.0.2564.116 (64-bit) reports the following in the console when using `rel="style"`:

> &lt;link rel=preload> must have a valid `as` value

**Comment by scottjehl** [comment]
Thanks @HugoGiraudel 

Does that version of chrome support rel=preload yet? I thought it was just canary still...

**Comment by HugoGiraudel** [comment]
As far as I can tell, it does not. However given the warning, I’m not sure…

**Comment by scottjehl** [comment]
Hmm. I enabled `Experimental Web Platform features` in chrome://flags in Chrome 49.0.2623.75 (latest, not Canary), and now I'm getting that warning for `as="stylesheet"`! Pretty confused now...

![image](https://cloud.githubusercontent.com/assets/214783/13542540/0cc518aa-e229-11e5-8bba-8487771e0c6c.png)

**Comment by scottjehl** [comment]
+ @igrigorik

**Comment by HugoGiraudel** [comment]
What the actual fuck? :(

**Comment by scottjehl** [comment]
Yoav's article has it listed as `style` here, but it's my code so it could be a mistake... https://www.smashingmagazine.com/2016/02/preload-what-is-it-good-for/#markup-based-async-loader

spec says `stylesheet` here: https://www.w3.org/TR/2015/WD-preload-20150721/

**Comment by scottjehl** [comment]
Chromium bug filed:
https://bugs.chromium.org/p/chromium/issues/detail?id=592139&q=preload%20style%20stylesheet&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified

**Comment by igrigorik** [comment]
http://w3c.github.io/preload/#attributes.. as=style, not stylesheet. This is due to a recent refactoring in Fetch.

**Comment by HugoGiraudel** [comment]
Damn… So 1.1 is incorrect. :(

**Comment by HugoGiraudel** [comment]
And Chrome 48 is wrong.

**Comment by yoavweiss** [comment]
Yeah, the spec refers to fetch and it was recently changed (and the implementation changed with it).

Also, That [spec](https://www.w3.org/TR/2015/WD-preload-20150721/) is an obsolete snapshot :/ Where did you find it?

**Comment by HugoGiraudel** [comment]
Thanks for your input @yoavweiss and @igrigorik. 

Now I guess we should release 1.2 to revert 1.1 change, @scottjehl. Sucks, I’m very sorry. :(

**Comment by scottjehl** [comment]
fair enough! Thanks for the feedback. I'll get that rolled back again. :)

**Comment by scottjehl** [comment]
1.2 is out, matching the state of the 1.0 release. All's well. Thanks for the quick feedback and have a nice weekend.
