### ISSUE TITLE
Success callback

### ISSUE THREAD

**Issue by adammcarth** [filamentgroup/loadCSS#15]
Is it currently possible (or easy to implement a feature that does so) to listen for a success callback function when the stylesheet has loaded successfully? Eg...

```javascript
loadCSS("stylesheet.css", null, null, function(status) {
    if (status === true) {
        console.log("Stylesheet injected.");
    } elseif (status === false) {
        console.log("Timeout or unsupported browser.");
    }
});
```

 I feel like this could be really useful, what do you guys think? Can you already do this?

**Comment by zachleat** [comment]
Fixed by https://github.com/filamentgroup/loadCSS/issues/47
