### ISSUE TITLE
onloadcss/polyfill, noscript

### ISSUE THREAD

**Issue by superpoincare** [filamentgroup/loadCSS#150]
How does onloadcss work with the polyfill? Do I manually add the onloadcss links for each stylesheet?

Also, I've noticed that noscript doesn't work without

`type="text/css"`

Just rel="stylesheet" won't do. So readme may need to be updated (unless I am doing something horribly wrong) - tested it in Chrome.

**Comment by akrawchyk** [comment]
The `onloadCSS` function works by passing in the preloading stylesheet elem returned from the manual call to the `loadCSS` function. However, the polyfill calls `loadCSS` automatically here https://github.com/filamentgroup/loadCSS/blob/f9ca33054d77c99cb146c4a48e43139a10194e16/src/cssrelpreload.js#L22.

Therefore, you can't get direct access to the stylesheets from `loadCSS` with the polyfill.

**Comment by scottjehl** [comment]
Hmm. If this is desirable, we might consider running the `link[rel=preload]` element's `onload` attribute value through onloadCSS.

**Comment by lydell** [comment]
If you look at the source code of onloadCSS.js, all it does is adding support for IE8 and Android < 4.4. If you don’t need to support those, the `onload` attribute is all you need.

I defined a function `window.__onloadCSS` (in an inline script) that I want to be called when the CSS has loaded. I simply added `window.__onloadCSS()` at the end of the `onload` attribute:

```html
<link rel="preload" href="/foo.css" as="style"
    onload="this.onload=null; this.rel='stylesheet'; window.__onloadCSS();">
```

That seems to work fine for me both in browsers that support rel=preload on those that don’t (that the polyfill takes care of).

**Comment by rasenplanscher** [comment]
@scottjehl Since the polyfill is standalone by now, this issue seems obsolete and can be closed, right?
