### ISSUE TITLE
W3 validation issues

### ISSUE THREAD

**Issue by Bernardus** [filamentgroup/loadCSS#162]
When validation my site i get the following errors

**Bad value preload for attribute rel on element link: The string preload is not a registered keyword.**

**Attribute as not allowed on element link at this point.**

How can i fix this to get my code validated?

**Comment by iLaurens** [comment]
The preload attribute specification is still a Working Draft from the Web Performance Working Group. So only when it gets accepted by W3C it would make sense to update the validator.

It's not a standard yet so the validator is right. It is up to you if you already want to adopt it this way and accept the warning from the validator.

**Comment by fabioformosa** [comment]
@Bernardus  W3C accepted preload attribute, but there was a bug in validator. A W3C developer read my [stackoverflow question](http://stackoverflow.com/questions/41331517/link-stylesheet-preload-vs-w3c-validation) and he's just fixed the validator!

**Comment by XhmikosR** [comment]
This is no longer an issue.
