### ISSUE TITLE
wrong link in readme?

### ISSUE THREAD

**Issue by raglannyc** [filamentgroup/loadCSS#166]
Hi sorry if this is the wrong spot for this but I don't know what I'm doing.

In the readme.md under "Recommended Usage Pattern" you say to include the loadCSS script but the link for that is to the onloadCSS.js file, which is what I was trying at first and of course it did not work. I looked at your example at http://filamentgroup.github.io/loadCSS/test/preload.html and saw I was using the wrong thing and figured it out, just might be nice to fix that link for novices like me :)

Thanks for the project!

**Comment by scottjehl** [comment]
I think this is fixed here on github now. Correct? https://github.com/filamentgroup/loadCSS

That said, we probably haven't pushed the readme update over to npm. Is that where you saw the bad link? Thanks

**Comment by raglannyc** [comment]
I downloaded loadCSS-1.2.0.zip from https://github.com/filamentgroup/loadCSS/releases

**Comment by scottjehl** [comment]
okay yep. I'll get a patch release up there to fix that. sorry for the trouble!

**Comment by scottjehl** [comment]
been fixed for a bit. closing.
