### ISSUE TITLE
CSSRelPreload does not pass media to loadCSS

### ISSUE THREAD

**Issue by pcfreak30** [filamentgroup/loadCSS#167]
On line 22, `w.loadCSS( link.href, link );` should be `w.loadCSS( link.href, link, link.getAttribute( "media" ) );`.

Thanks.

**Comment by rsteinwand** [comment]
I wonder if this fixes the issue for ie8 https://github.com/filamentgroup/loadCSS/issues/112

I'll have to check on Tuesday.

**Comment by rsteinwand** [comment]
No this does not fix #112 in IE8.

**Comment by Kravimir** [comment]
Fortunately this is easy to add, but it is a strange omission from the script,

Taking into account the goal of keeping the script as short as possible, I suggest using "link.media" instead of "link.getAttribute('media')".

**Comment by larssn** [comment]
Weird omission indeed, easy fix. Thanks for posting this.

**Comment by scottjehl** [comment]
seems reasonable. We'll take a look, thanks
