### ISSUE TITLE
Possibly dumb question, but where do I load loadCSS.js - header?

### ISSUE THREAD

**Issue by dylanh724** [filamentgroup/loadCSS#168]
For the most efficiency, I put script for loadCSS.js in the header just before the script to call loadCSS, in-line?

then onload and csspreload I dont have to script (loadCSS references it in same location?)

Thanks for clarification

Example:

```
<head>
<!-- some meta scripts here -->
<script src='js/loadCSS.js' type='text/javascript'></script>
    <script>
        /*!
         loadCSS: load a CSS file asynchronously.
         [c]2014 @scottjehl, Filament Group, Inc.
         Licensed MIT
         */
        function loadCSS( href, before, media ){
            "use strict";
            var ss = window.document.createElement( "link" );
            var ref = before || window.document.getElementsByTagName( "script" )[ 0 ];
            var sheets = window.document.styleSheets;
            ss.rel = "stylesheet";
            ss.href = href;
            ss.media = "only x";
            ref.parentNode.insertBefore( ss, ref );
            function toggleMedia(){
                var defined;
                for( var i = 0; i < sheets.length; i++ ){
                    if( sheets[ i ].href && sheets[ i ].href.indexOf( href ) > -1 ){
                        defined = true;
                    }
                }
                if( defined ){
                    ss.media = media || "all";
                }
                else {
                    setTimeout( toggleMedia );
                }
            }
            toggleMedia();
            return ss;
        }
        loadCSS( "css/normalize.css" );
```

**Comment by vlrprbttst** [comment]
you don't need `<script src='js/loadCSS.js' type='text/javascript'></script>` to be included.

my stylesheet appends to `<body>` instead of `<head>`, is this normal?

**Comment by vijayaraghavanramanan** [comment]
@

You don't need `script src` as @vlrprbttst said. 

Also you are missing the closing `</script>` tag. 

About placement: you first insert the inline styles and then loadcss. 

`<style>
/* inline css here */
</style>
<script>
//loadcss + preloadcss inlined here.
</script>`

Google Chrome has preload now, so you should not just use loadCSS but use it as a polyfill. See readme.

**Comment by vlrprbttst** [comment]
@dylanh724 what about my stylesheet appending to <body> instead of <head>? 😄

**Comment by scottjehl** [comment]
Please see the latest readme. Should be clearer now, thanks
https://github.com/filamentgroup/loadCSS/blob/master/README.md
