### ISSUE TITLE
Please re-open #112 (IE 8 behaviour)

### ISSUE THREAD

**Issue by rsteinwand** [filamentgroup/loadCSS#169]
https://github.com/filamentgroup/loadCSS/issues/112

I have a couple of pages using loadcss. Everything else I rolled back.

If you go here: http://www.intercepteft.com/achprocessing.html (page uses loadCSS)
Then click on ContactUs link at the top of the page, you'll get a print style sheet. Then hit "back" in your browser and the first page will also be a print style sheet.

I tried the fix suggested in #167, but that didn't help (but I'm still using it).

FWIW, this also affects IE7 (but who cares).

Thanks.

**Comment by rsteinwand** [comment]
There was a little discussion about this issue here: https://github.com/filamentgroup/loadCSS/issues/175

Using an external print style sheet does fix this issue until you don't have to worry about IE8.

**Comment by scottjehl** [comment]
reopened #112
