### ISSUE TITLE
deferred css attached to body

### ISSUE THREAD

**Issue by vlrprbttst** [filamentgroup/loadCSS#170]
this is my script

```
...
<script charset="utf-8">
      function loadCSS( href, before, media ){
          "use strict";
          var ss = window.document.createElement( "link" );
          var ref = before || window.document.getElementsByTagName( "script" )[ 0 ];
          var sheets = window.document.styleSheets;
          ss.rel = "stylesheet";
          ss.href = href;
          ss.media = "only x";
          ref.parentNode.insertBefore( ss, ref );
          function toggleMedia(){
              var defined;
              for( var i = 0; i < sheets.length; i++ ){
                  if( sheets[ i ].href && sheets[ i ].href.indexOf( href ) > -1 ){
                      defined = true;
                  }
              }
              if( defined ){
                  ss.media = media || "all";
              }
              else {
                  setTimeout( toggleMedia );
              }
          }
          toggleMedia();
          return ss;
      }
      loadCSS( "css/main.css" );
</script>
</body>
```

I just noticed the css is loaded first thing in `<body>`, is it supposed to be this way? should i put the script in head instead? is there a way to keep it there but append the css in `head`?

thanks!

**Comment by rsteinwand** [comment]
Are you using the recommended install? https://github.com/filamentgroup/loadCSS

<link rel="preload" href="path/to/mystylesheet.css" as="style" onload="this.rel='stylesheet'">

With that markup in the head of your page, include the loadCSS script, as well as the loadCSS rel=preload polyfill script in your page (inline to run right away, or in an external file if the CSS is low-priority).

When I check mine with Firefox, the css is in the head, right where I put it.

**Comment by vlrprbttst** [comment]
would this work then?

```
<head>
<link rel="preload" href="css/main.css" as="style" onload="this.rel='stylesheet'">
<noscript><link rel="stylesheet" href="css/main.css"></noscript>
</head>
<body>
stuff
<script charset="utf-8">
      function loadCSS( href, before, media ){
          "use strict";
          var ss = window.document.createElement( "link" );
          var ref = before || window.document.getElementsByTagName( "script" )[ 0 ];
          var sheets = window.document.styleSheets;
          ss.rel = "stylesheet";
          ss.href = href;
          ss.media = "only x";
          ref.parentNode.insertBefore( ss, ref );
          function toggleMedia(){
              var defined;
              for( var i = 0; i < sheets.length; i++ ){
                  if( sheets[ i ].href && sheets[ i ].href.indexOf( href ) > -1 ){
                      defined = true;
                  }
              }
              if( defined ){
                  ss.media = media || "all";
              }
              else {
                  setTimeout( toggleMedia );
              }
          }
          toggleMedia();
          return ss;
      }
      loadCSS( "css/main.css" );
</script>
</body>
```

**Comment by vlrprbttst** [comment]
no it doesn't, here's the output :)


![](http://i.imgur.com/BH4JPQO.png)

what am i missing?

**Comment by rsteinwand** [comment]
Drop:loadCSS("css/main.css")
Add cssrelpreload script.

Or use mine:

`<script type=text/javascript>!function(e){"use strict";var t=function(t,n,r){function o(e){return i.body?e():void setTimeout(function(){o(e)})}function a(){d.addEventListener&&d.removeEventListener("load",a),d.media=r||"all"}var l,i=e.document,d=i.createElement("link");if(n)l=n;else{var s=(i.body||i.getElementsByTagName("head")[0]).childNodes;l=s[s.length-1]}var u=i.styleSheets;d.rel="stylesheet",d.href=t,d.media="only x",o(function(){l.parentNode.insertBefore(d,n?l:l.nextSibling)});var f=function(e){for(var t=d.href,n=u.length;n--;)if(u[n].href===t)return e();setTimeout(function(){f(e)})};return d.addEventListener&&d.addEventListener("load",a),d.onloadcssdefined=f,f(a),d};"undefined"!=typeof exports?exports.loadCSS=t:e.loadCSS=t}("undefined"!=typeof global?global:this),function(e){if(e.loadCSS){var t=loadCSS.relpreload={};if(t.support=function(){try{return e.document.createElement("link").relList.supports("preload")}catch(t){return!1}},t.poly=function(){for(var t=e.document.getElementsByTagName("link"),n=0;n<t.length;n++){var r=t[n];"preload"===r.rel&&"style"===r.getAttribute("as")&&(e.loadCSS(r.href,r,r.getAttribute("media")),r.rel=null)}},!t.support()){t.poly();var n=e.setInterval(t.poly,300);e.addEventListener&&e.addEventListener("load",function(){e.clearInterval(n)}),e.attachEvent&&e.attachEvent("onload",function(){e.clearInterval(n)})}}}(this);</script>`

**Comment by vlrprbttst** [comment]
i now have this:

```
<head>
<link rel="preload" href="css/main.css" as="style" onload="this.rel='stylesheet'">
<noscript><link rel="stylesheet" href="css/main.css"></noscript>
</head>
<body>
stuff
<script charset="utf-8">
(function( w ){
// rel=preload support test
if( !w.loadCSS ){
return;
}
var rp = loadCSS.relpreload = {};
rp.support = function(){
try {
  return w.document.createElement( "link" ).relList.supports( "preload" );
} catch (e) {
  return false;
}
};

// loop preload links and fetch using loadCSS
rp.poly = function(){
var links = w.document.getElementsByTagName( "link" );
for( var i = 0; i < links.length; i++ ){
  var link = links[ i ];
  if( link.rel === "preload" && link.getAttribute( "as" ) === "style" ){
    w.loadCSS( link.href, link );
    link.rel = null;
  }
}
};

// if link[rel=preload] is not supported, we must fetch the CSS manually using loadCSS
if( !rp.support() ){
rp.poly();
var run = w.setInterval( rp.poly, 300 );
if( w.addEventListener ){
  w.addEventListener( "load", function(){
    w.clearInterval( run );
  } );
}
if( w.attachEvent ){
  w.attachEvent( "onload", function(){
    w.clearInterval( run );
  } )
}
}
}( this ));
</script>
</body>
```

and i get this output:

![](http://i.imgur.com/BBzHbu0.png)

would this be ok?

clicking on `<link rel="stylesheet" href="css/main.css" as="style" onload="this.rel='stylesheet'">` goes to the correct css file

**Comment by rsteinwand** [comment]
You need the loadCSS and cssrelpreload.js scripts. 

For Chrome (or Opera), all you need is this for it to work:
`<link rel="preload" href="css/main.css" as="style" onload="this.rel='stylesheet'">`

So to test your script, you need to use a different browser. http://caniuse.com/#feat=link-rel-preload
