### ISSUE TITLE
CommonJS module for onloadCSS

### ISSUE THREAD

**Issue by SirRawlins** [filamentgroup/loadCSS#171]
I'm pulling loadCSS in through NPM and requiring it using Browserify. However the additional onloadCSS doesn't appear to be wrapped as a CJS module which makes requiring it a challenge.

Has this been left out for a specific reason? or is it just an oversight? Happy to send in a PR if we want it done.

**Comment by yoyurec** [comment]
oh! the same issue (((
my ugly solution was
```
var loadCSS = require('fg-loadcss/src/loadCSS.js');
window.inlined = loadCSS;
``` 
and then 
```
inlined.loadCSS('app.css');
```
BUT! when i tried to switch to new way with `rel=preload` i got an issue
```
require('fg-loadcss/src/loadCSS.js');
var cssrelpreload = require('fg-loadcss/src/cssrelpreload.js');
window.inlined = cssrelpreload;
```
and then
```
inlined.cssrelpreload('app.css');
```
in this case `cssrelpreload` didn't see `loadCSS` ((

**Comment by SirRawlins** [comment]
@yoyurec I think your issue is different to mine (unless I've misunderstood what you're saying)

**Comment by Kilbourne** [comment]
Same problem for preload poly.

**Comment by jhabdas** [comment]
@SirRawlins Have you considered shimming in your own wrapper?

**Comment by SirRawlins** [comment]
Been a while since I looked at it Josh, but may well back back on this
project before long and can take another look.

**Comment by jhabdas** [comment]
I believe UMD is compatible with CJS. If so, perhaps this will work:
https://cdn.jsdelivr.net/fetch-inject/latest/fetch-inject.umd.min.js

And as a fallback for older browsers, you can skip the need to polyfill fetch:
https://github.com/jhabdas/fetch-inject#progressive-enhancement

**Comment by rasenplanscher** [comment]
Hey folks,
I'm currently working on a v3 and leaning toward merging `onloadCSS` into `loadCSS` and bringing back the callback option in some way.

Would that be a good fit or is there a use-case for `onloadCSS` without `loadCSS`?

**Comment by rasenplanscher** [comment]
After looking into merging `onloadCSS` into `loadCSS` I've come to the conclusion that it's not worth the trouble at present. I have therefore stuck with the current split and added build targets for CJS, ESM, and global/window property-setting. It's all in #298
