### ISSUE TITLE
About the main file

### ISSUE THREAD

**Issue by x09326** [filamentgroup/loadCSS#173]
Hi, I'm going to host this lib on [cdnjs](https://cdnjs.com).

Because I need to config npm auto-update.
But I don't know which files I should add.
Can you help me? Or just create a **dist** folder and put the files in there.

Thanks!
https://github.com/cdnjs/cdnjs/issues/7961

**Comment by pothi** [comment]
That would be kind of you to host loadCSS using a CDN. However, I wouldn't recommend loading it from a CDN, as loadCSS is not a big file. The [un-minified file](https://github.com/filamentgroup/loadCSS/blob/master/src/loadCSS.js) is already too small (at around 2.4k). If minified, it comes to less than 800 bytes. Having it gzipped would make it even lesser.

**Comment by scottjehl** [comment]
Thanks. We offer this lib on NPM but not on CDNs, as it's intended to be inlined (though h2 push is fine as well). We'll be updating our releases with dist files soon though.
