### ISSUE TITLE
"Chrome Mac" and "Opera Mac"

### ISSUE THREAD

**Issue by JoeArizona** [filamentgroup/loadCSS#175]
Hi FG – I was thrown by the support table saying "Chrome Mac" and "Opera Mac" with no mention of Chrome for Windows or Opera for Windows. I assume that Mac vs Windows doesn't matter for desktop browser support for loadCSS right? I just wanted to make sure.

Also, does it work fine with Edge and Brave?

Thanks,

Joe

**Comment by rsteinwand** [comment]
Chrome Windows and Edge both work. The only issue I have is IE7/8 deliver a print style sheet.

This site has 1.2.0 installed if you want to test: http://www.tpppa.org/

**Comment by scottjehl** [comment]
@rsteinwand  are you unable to link to your print stylesheet ordinarily? I'd recommend doing that instead of using loadCSS. It'll load without blocking due to the print media type.

**Comment by rsteinwand** [comment]
I only have one external style sheet and the print section is the last dozen lines preceded with:
`@media print{}`

I have critical css inlined with the page and use LoadCSS to load the remaining css.

**Comment by rsteinwand** [comment]
I see the TPPPA site I linked above doesn't have a problem with the print style sheet, but the only print code there is one line:

`@media print{.nav{display:none}.pagetop{margin-top:0}}`

I'll play with it more and see what I can figure out.

THANKS.

**Comment by scottjehl** [comment]
Hi! Could I ask for a brief recap on the issue we need to address here? I'm trying to triage the issue tracker and some of these are hard to tell if they're still an issue we need to fix.

**Comment by scottjehl** [comment]
The readme table is gone now, replaced with a note that the CSS will block rendering like in IE8 and older as if it was a normal stylesheet link
