### ISSUE TITLE
The problem with PageSpeed and validator.w3.org

### ISSUE THREAD

**Issue by Akela-SF** [filamentgroup/loadCSS#176]
I am sorry for my very bad english.

Your script is running well. But to say about this script - "works great" - need to fix two small problems:
1 - when checking the site PageSpeed Insignts not loaded CSS files
2 - https: //validator.w3.org swears on the wrong attribute (as = "style")

![psi](https://cloud.githubusercontent.com/assets/11997526/15719775/2ce0628c-283a-11e6-9544-51042817ab3c.PNG)

and

![vw3](https://cloud.githubusercontent.com/assets/11997526/15719859/8426c946-283a-11e6-9986-ebfddc469159.PNG)

**How to fix these errors?**

in the `<head>` are connected -  `<script>loadCSS.js + cssrelpreload.js + onloadCSS.js</script>`

  `<link href="assets/css/combined.min.css" rel="preload" type="text/css" crossorigin= "anonymous" media='all' property='link' as="style" onload="this.rel='stylesheet'">` 
  `<link href="css/team.css" rel="preload" type="text/css" crossorigin= "anonymous" media='all' property='link' as="style" onload="this.rel='stylesheet'">`
  `<noscript>` 
  `<link href="assets/css/combined.min.css" rel="stylesheet" type="text/css" crossorigin= "anonymous" media='all' property=''>`
 `<link href="css/team.css" rel="stylesheet" type="text/css" crossorigin= "anonymous" media='all' property=''>`
  `</noscript>`

**Comment by rsteinwand** [comment]
The W3 validation issue is covered here: https://github.com/filamentgroup/loadCSS/issues/162

I suspect you should try testing with a simpler page.

**Comment by scottjehl** [comment]
The PSI example is hard to reproduce, but with our test page it seems to report as expected. I suspect PSI uses chrome, which does not receive a loadCSS polyfill anyway since it supports rel=preload. https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fmaster-origin-loadcss.fgview.com%2Ftest%2Fpreload-switch.html
