### ISSUE TITLE
Question: LoadCSS with LocalStorage

### ISSUE THREAD

**Issue by MarcoKunz** [filamentgroup/loadCSS#18]
Hello @scottjehl 

Is there a good solution to go with loadCSS in combination with the power that comes with localStorage.

The way I want to go down is like this:

- loadCSS will load a stylesheet asynchronously
- then the script will check if localStorage is there
  - if it is there we put the stylesheet there and prevent the script from being loaded on revisit
    - stylesheet will be loaded from localStorage from now on
    - the script will check the localStorage for the CSS file
  - it is not there, nothing happens and the world keeps on revolving
    - back to step one on revisit/next page load

That would be much better than any cookie-based solution anyways but the main advantage I see is, that apart from loading CSS asynchronously, we could prevent the script from firing everytime a user is requesting a page in a website.

My questions:
What do you think?
How could one build that (I'm too bad at writing JS, otherwise I would have pasted a possible solution with my question)?
May be that has been thought of already and I just couldn't see it?

**Comment by zachleat** [comment]
Yeah, this is something we’ve talked about specifically with fonts a couple of times. I believe @scottjehl did some WebPageTest runs showing that localStorage caused a much slower initial render time, so we usually just rely on web browser cache for this.

Also, keep in mind that this utility is a complement to `<link>` based stylesheet loading, so it will work cross domain out of the box. A change to using an XHR based approach would require additional CORS configuration and probably more overhead than we’d want compared to what we have currently.

Does that make sense?

I’m going to close this for now, please reopen if you have additional comments or questions!
