### ISSUE TITLE
Not working in Firefox, IE, or Edge if the link tag appears after the polyfill

### ISSUE THREAD

**Issue by fatjester** [filamentgroup/loadCSS#180]
Currently the polyfill script only works if the link tag with the css appears before the polyfill script (current versions of Firefox and IE).

Example using original demo with link tag moved to after the script (view in firefox, IE or Edge):
http://s.codepen.io/fatjester/debug/gMMrxv

**Comment by scottjehl** [comment]
I've tested the following page (which has scripts before link) in FF, Edge, and IE latest. Confirming this now works.
