### ISSUE TITLE
loadCSS and document.ready not going well togheter

### ISSUE THREAD

**Issue by vlrprbttst** [filamentgroup/loadCSS#182]
I'm managing my above the fold css with https://github.com/addyosmani/critical and loading my main .css asynchronously with your function but i notice this creates some problems with my javascript.

my .js sets heights to divs for example, or calculates offset.top() of a bunch of elements and they are all in a document ready function. The problem is that the .js kicks in before the page is in its final state, so the results are unexpected and i'm having rendering issues.

how would you tackle this problem? cause nobody talks about this and it's a pretty big deal in my opinion.

**Comment by scottjehl** [comment]
@vlrprbttst We don't tend to do a lot of JS-based layout calculation but I can understand the use case I think. 

If particular CSS rules are "critical" to be present when your JS kicks in, you might decide to force those rules to be included in your critical css. I can't speak to the critical script you linked, but in [the critical css task we maintain](https://github.com/filamentgroup/grunt-criticalcss), we have an option to "forceInclude" selectors that contain a particular string. I'm pretty sure Addy's does too (we might have even gotten the idea from him!).

Alternatively, you might consider listening for either a load event or presence of your stylesheet in the DOM to kick off your JS execution.

**Comment by vlrprbttst** [comment]
> you might consider listening for either a load event or presence of your stylesheet in the DOM to kick off your JS execution.

any hint on this? 😄  because now that I think of it, it's actual not only css but the js itself. one clear issue is with the match Height plugin for example (http://brm.io/jquery-match-height/). this one in particular kicks in too early, setting wrong heights because the page didn't fully render.

thanks for your help!

**Comment by johanson** [comment]
@vlrprbttst This is what [onloadCSS.js](https://github.com/filamentgroup/loadCSS/blob/master/src/onloadCSS.js) is for? Make the plugin kick in after your CSS is fetched.

**Comment by vlrprbttst** [comment]
i tried it this way:

in <head> i have this:

```
      function loadCSS( href, before, media ){
          "use strict";
          var ss = window.document.createElement( "link" );
          var ref = before || window.document.getElementsByTagName( "script" )[ 0 ];
          var sheets = window.document.styleSheets;
          ss.rel = "stylesheet";
          ss.href = href;
          ss.media = "only x";
          ref.parentNode.insertBefore( ss, ref );
          function toggleMedia(){
              var defined;
              for( var i = 0; i < sheets.length; i++ ){
                  if( sheets[ i ].href && sheets[ i ].href.indexOf( href ) > -1 ){
                      defined = true;
                  }
              }
              if( defined ){
                  ss.media = media || "all";
              }
              else {
                  setTimeout( toggleMedia );
              }
          }
          toggleMedia();
          return ss;
      }
      loadCSS( "css/main.css" );

      function onloadCSS( ss, callback ) {
	var called;
	function newcb(){
			if( !called && callback ){
				called = true;
				callback.call( ss );
			}
	}
	if( ss.addEventListener ){
		ss.addEventListener( "load", newcb );
	}
	if( ss.attachEvent ){
		ss.attachEvent( "onload", newcb );
	}
 	if( "isApplicationInstalled" in navigator && "onloadcssdefined" in ss ) {
		ss.onloadcssdefined( newcb );
	}
}
```

and at the bottom of the page I have, near the body closing, in a main.js file:

```
    ....
    var stylesheet = loadCSS( "css/main.css" );
    onloadCSS( stylesheet, function() {
        console.log( "Stylesheet has loaded." );
        // the two init of the problematic plugins
        $('.header > div').matchHeight();
        stickyNav();
    });

}); //document ready
```

but I get the same exact rendering errors I had before. :/ what am i missing?

**Comment by chrisvanpatten** [comment]
I'm having some issues w/ this too. the `onloadCSS` method is a start, but not perfect. There seem to be a few milliseconds between when the callback is triggered and when the browser actually repaints the screen (possibly also a delay in the initial CSS download too; I seem to have fewer issues with caching enabled).

A setTimeout delay is the easy way to fix this, but it's definitely not ideal. Obviously moving CSS that influences the JS calculations is the best way to go if you can, but that's not always possible.

One option I'm considering is setting a listener on a specific element and waiting for it to match specific CSS conditions that are included in the non-critical CSS file, then triggering an event when those conditions are met (e.g. every 10ms, check to see if div#check's offsetHeight is greater than 100px; if true, trigger event X; if false, keep checking). Not sure what the effect on performance would be, but it would work at least in theory.
