### ISSUE TITLE
Page Speed Insights not loading CSS files

### ISSUE THREAD

**Issue by muhammad-adnan** [filamentgroup/loadCSS#183]
Hi First of All thanks for making this wonderfull script.   From last one week me doing fighting with Google for remove blocking resources,  tried all solution on internet but no one work & my all efforts are failed  except your Solution is really great achievement by you and your teams  That is why me suggest to all use this.  Do not waste time on other solution. Now after long try research not able to found the solution of this minor thing.  

My site working fine but when checking the site PageSpeed Insignts then not loaded CSS files in page insight side bar on test preview.  Because of this issue me facing Consider fixing issue : Size tap targets appropriately. Rest is working fine 

https://developers.google.com/speed/pagespeed/insights/?url=www.grafdom.net%2Fprojects%2Fma%2Fnewed%2F 

Anyone help then this great for me

Thanks

**Comment by rsteinwand** [comment]
Try moving your stylesheets BEFORE LoadCSS scripts.

Also, you should add critical css to your <head> if you're going to use this loadCSS OR just load non-critical css with loadCSS. https://jonassebastianohlsson.com/criticalpathcssgenerator/

**Comment by scottjehl** [comment]
This seems to be fixed now but please let us know if not.
Example here: https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fmaster-origin-loadcss.fgview.com%2Ftest%2Fpreload-switch.html
