### ISSUE TITLE
Network latency can cause css to block render in some cases.

### ISSUE THREAD

**Issue by scottjehl** [filamentgroup/loadCSS#19]
I noticed this when testing over 3g. Sometimes, our timeout is fast enough to toggle the `link`'s `media` attribute to `all` before its stylesheet request goes out, and it ends up blocking render. Not good.

One workaround I've come up with so far involves polling the `document.styleSheets` array until it increments, which I've found is a safe time to toggle the `media` attribute on any connection speed, as the request appears to be in flight at the point it joins that array (yet it's still long before `onload`, which is good for minimizing the times this logic would have to run). That change looks something like this:

``` js
/*!
loadCSS: load a CSS file asynchronously.
[c]2014 @scottjehl, Filament Group, Inc.
Licensed MIT
*/
function loadCSS( href, before, media ){
    "use strict";
    // Arguments explained:
    // `href` is the URL for your CSS file.
    // `before` optionally defines the element we'll use as a reference for injecting our <link>
    // By default, `before` uses the first <script> element in the page.
    // However, since the order in which stylesheets are referenced matters, you might need a more specific location in your document.
    // If so, pass a different reference element to the `before` argument and it'll insert before that instead
    // note: `insertBefore` is used instead of `appendChild`, for safety re: http://www.paulirish.com/2011/surefire-dom-element-insertion/
    var ss = window.document.createElement( "link" );
    var ref = before || window.document.getElementsByTagName( "script" )[ 0 ];
    var ssLength = window.document.styleSheets.length;
    ss.rel = "stylesheet";
    ss.href = href;
    // temporarily, set media to something non-matching to ensure it'll fetch without blocking render
    ss.media = "only x";
    // inject link
    ref.parentNode.insertBefore( ss, ref );
    // This function sets the link's media back to `all` so that the stylesheet applies once it loads
    // It is designed to loop until document.styleSheets includes
    function toggleMedia(){
        if( window.document.styleSheets.length > ssLength ){
            ss.media = media || "all";
        }
        else {
            setTimeout( toggleMedia );
        }
    }

    toggleMedia();
    return ss;
 }
```

This works generally, but a downside to it is it may not work well with multiple `loadCSS` calls, since they'll all toggle their media as soon as the first call goes out. I think we might be able to work around this by queueing the media toggles in the order they're called. Maybe a `loadCSS.locked` property would give us that sort of mechanism. The queue wouldn't incur much delay, since it's not about waiting for requests to return so much as ensuring the stylesheets have joined the CSSOM. 

Since it's high-priority, we'll try and close this one out in the morning.

**Comment by zachleat** [comment]
For posterity, the `document.styleSheets` addition after load is a WebKit/Blink behavior. In Gecko the `document.styleSheets` addition happens immediately after the stylesheet node is appended to the document.

Probably worth testing on a Firefox phone, if anyone has one.
