### ISSUE TITLE
Print stylesheet not loading

### ISSUE THREAD

**Issue by rkedde** [filamentgroup/loadCSS#191]
The print stylesheet isn't loading when printing.

Implemented this like:
`<link rel="preload" href="/css/print.css" media="print" as="style" onload="this.rel='stylesheet'"/>
`

Any ideas?

**Comment by johanson** [comment]
Print stylesheets are non-blocking by default. Include a stylesheet like you would normally do.

**Comment by rkedde** [comment]
Thank's for your quick response.
