### ISSUE TITLE
Weird behavior with font loaders on iOS

### ISSUE THREAD

**Issue by diniscorreia** [filamentgroup/loadCSS#192]
I've been trying to debug this all afternoon and no luck.

I'm using both loadCSS and fontfaceobserver - and apparently somethings break in fontfaceobserver if I use loadCSS (fontfaceobserver's promise don't always resolve). 

I've tried using webfontloader as well, and the same thing happens. 

I have the following elements on the page:
- critical inline css
- inline loadCSS and rel=preload polyfill (and font loader)
- stylesheet link with rel=preload
- inline script  that runs load css and font loader

It happens with either a link or using the preloadCSS function. Only happens on iOS (both Safari and Chrome).

I'm not sure if this is a bug on the font loaders, but it's weird that it breaks both webfontload fontfaceobserver. 

Any ideas? :\

**Comment by zachleat** [comment]
Do you have a test case?

**Comment by diniscorreia** [comment]
@zachleat 

Apologies for the huge chunk of inline CSS and the mess que the JS, been trying everything for the last couple of hours: http://diniscorreia.com/debug/fontface.html

If I open it on iOS the fonts fontfaceobserver Promise won't resolve (but the fonts do show up in the network tab); works fine on other browser. If don't call loadCSS, it works.

**Comment by diniscorreia** [comment]
Quick update: weirdly enough, it almost seem like a race condition. If I test it locally it with a local css file, it works most of the times (I still fails sometimes, but not as often).

**Comment by johanson** [comment]
@diniscorreia Is there a reason you're not using the [recommended method of using loadCSS](https://github.com/filamentgroup/loadCSS#recommended-usage-pattern)?
Any why are you then using rel=preload polyfill?

**Comment by diniscorreia** [comment]
@johanson I was, actually. I though it could be caused by it so I tried calling the function directly. 

Just updated the test case with the recommended method - same problem.

**Comment by johanson** [comment]
@diniscorreia You have the timeout for fontfaceobserver 3000ms.
Most likely, when testing on mobile (different network? slower?), it is not enough time (since the fonts are loaded async).
rel="preload" is not supported on iOS natively, hence it takes even more time compared to native support.
Use Chrome dev console and emulate slow network and you can reproduce the bug. I don't think it has anything to do with loadCSS besides the fact it takes more time because you're not waiting for the fonts to load before rendering the page.

**Comment by diniscorreia** [comment]
@johanson tried that already - throttling set to 2G or GPRS and it stills works. Also tried on Safari (same wireless network than the iOS devices), which also doesn't support rel preload, and it works.

Also tried increasing timeout - no luck.

By the way, my font-face declarations are inlined on the critical css, so fontfaceobserver doesn't have to wait for the linked css to load.

**Comment by zenderol** [comment]
I can also confirm this issue. It happens only when using the included polyfil (cssrelpreload.js)

**Comment by diniscorreia** [comment]
Somehow this seems to be related to two Safari 10 font loading API bugs. 

[fontfaceobserver was updated](https://github.com/bramstein/fontfaceobserver/pull/86) to disable native font loading on Safari 10.
