### ISSUE TITLE
Dom Elements Flicker before CSS is loaded

### ISSUE THREAD

**Issue by sscho** [filamentgroup/loadCSS#194]
Hi guys,

Chrome Version 51.0.2704.79 Ubuntu 14.04 (64-bit)
NodeJS/Express App

Before my CSS is loaded, the document elements appear on the screen, unstyled. It looks really ugly, and i'd like to somehow have it wait until the CSS is done loading...which kind of defeats the purpose of all this. Is there a way to have all the elements display none before the CSS shows up? 

Perhaps I'm implementing this wrong. Here's my code:

```
<script>
  /*! loadCSS: load a CSS file asynchronously. [c]2016 @scottjehl, Filament Group, Inc. Licensed MIT */
  (function(w){
    "use strict";
    /* exported loadCSS */
    var loadCSS = function( href, before, media ){
      var doc = w.document;
      var ss = doc.createElement( "link" );
      var ref;
      if( before ){
        ref = before;
      }
      else {
        var refs = ( doc.body || doc.getElementsByTagName( "head" )[ 0 ] ).childNodes;
        ref = refs[ refs.length - 1];
      }

      var sheets = doc.styleSheets;
      ss.rel = "stylesheet";
      ss.href = href;
      ss.media = "only x";

      function ready( cb ){
        if( doc.body ){
          return cb();
        }
        setTimeout(function(){
          ready( cb );
        });
      }
      ready( function(){
        ref.parentNode.insertBefore( ss, ( before ? ref : ref.nextSibling ) );
      });
      var onloadcssdefined = function( cb ){
        var resolvedHref = ss.href;
        var i = sheets.length;
        while( i-- ){
          if( sheets[ i ].href === resolvedHref ){
            return cb();
          }
        }
        setTimeout(function() {
          onloadcssdefined( cb );
        });
      };

      function loadCB(){
        if( ss.addEventListener ){
          ss.removeEventListener( "load", loadCB );
        }
        ss.media = media || "all";
      }
      if( ss.addEventListener ){
        ss.addEventListener( "load", loadCB);
      }
      ss.onloadcssdefined = onloadcssdefined;
      onloadcssdefined( loadCB );
      return ss;
    };
    if( typeof exports !== "undefined" ){
      exports.loadCSS = loadCSS;
    }
    else {
      w.loadCSS = loadCSS;
    }
  }(typeof global !== "undefined" ? global : this));
  loadCSS('/main/css/base.min.css')
</script>

<link rel="preload" href="/main/css/base.min.css" as="style" onload="this.rel='stylesheet'">
<noscript>
  <link rel="stylesheet" href="/main/css/base.min.css">
</noscript>
```

**Comment by johanson** [comment]
But the purpose of this project is to load CSS asynchronously.

You should inline your critical CSS for everything critical, above-the-fold content first. Everything that doesn't cause repaints. You can hide the elements you don't show in your inline CSS.

By the look of it, you don't need this project and you would be better off by loading your CSS in traditional (blocking) way.

**Comment by rsteinwand** [comment]
If you want to use LoadCSS you need to create the critical CSS and inline it in your head, potentially a lot of work considering this is the critical css for one page and other pages may differ. Here's the tool I used: https://jonassebastianohlsson.com/criticalpathcssgenerator/

Otherwise, like Johanson said, simply go back to the traditional way of loading style sheets.

**Comment by sscho** [comment]
Thanks, makes sense. I'll go back to using CSS the pleb way.
