### ISSUE TITLE
Doesn't work on Safari

### ISSUE THREAD

**Issue by zaibacu** [filamentgroup/loadCSS#195]
Safari version: Version 10.0.1 (12602.2.14.0.7)

No css is loaded, at all. Tested on Chrome - works like a charm.

**Comment by rsteinwand** [comment]
Link?

**Comment by scottjehl** [comment]
We tested http://filamentgroup.github.io/loadCSS/test/preload.html in Safari and can't reproduce a problem. Please provide a link if you need help and we'll take a look.

**Comment by gravyraveydavey** [comment]
It sounds like you were missing the polyfill, which just caught me out also. If you're using bower to include loadcss be sure to also include the polyfill adding it to your bower overrides.

`    "loadcss": {
      "main": [
        "./src/loadCSS.js",
        "./src/cssrelpreload.js"
      ]
    },`

**Comment by aastik1208** [comment]
loadCSS("<%= stylesheet_path('application') %>");
This code is not interpreted in safari, how to write this.
