### ISSUE TITLE
Flash of Unstyled Text (FOUT) first load in Firefox and Safari

### ISSUE THREAD

**Issue by yer-ly** [filamentgroup/loadCSS#198]
When using Google web fonts Firefox and Safari will load all the styles (colors, layout,etc.) first and then at the very end, all the fonts will be applied. Is this supposed to happen or is this a bug?

**Comment by zachleat** [comment]
Do you mean a Flash of Invisible Text (FOIT)?

Just a reminder that web font loading is a separate loading cycle from the CSS. Using `loadCSS` to load the Google web font stylesheets will load only the stylesheet asynchronously. The web font probably downloads after the stylesheet has loaded.

I wrote an article about why this happens here: https://www.zachleat.com/web/lazy-loading-webfonts/

Please reopen if you have more questions!
