### ISSUE TITLE
google page speed insight problems

### ISSUE THREAD

**Issue by TimJans** [filamentgroup/loadCSS#199]
hi there,

did everything by the book , put my stylesheets in the head like this:

```
<link rel='preload' href='my-styles-01.css' as='style' onload='this.rel=\"stylesheet\"'><noscript><link rel='stylesheet' href='my-styles-01.css'></noscript>
<link rel='preload' href='my-styles-02.css' as='style' onload='this.rel=\"stylesheet\"'><noscript><link rel='stylesheet' href='my-styles-02.css'></noscript>
<link rel='preload' href='my-styles-03.css' as='style' onload='this.rel=\"stylesheet\"'><noscript><link rel='stylesheet' href='my-styles-03.css'></noscript>
```

(yeah, the 3 files are necessary...) loadcss does what it should. still, google page speed insights complains the above mentioned files block page rendering and gives me bad scores.

ideas anyone?

cheers in advance

**Comment by odahcam** [comment]
If you want, you could use the `loadCSS(my-styles-01.css);` JavaScript function to avoid this.

**Comment by nigrosimone** [comment]
same for me...

**Comment by TimJans** [comment]
update: not a loadCSS but a critical css issue. google page score improved once i optimized the critical path inline css.
