### ISSUE TITLE
Google Page Insight and script inclusion order

### ISSUE THREAD

**Issue by fabioformosa** [filamentgroup/loadCSS#200]
Hi, 
first of all, I would thank for this useful project.

I'm experiencing some troubles with Google Page Insight. It reports all css marked with "preload rel" as blocking resources.
I'm following the [recommended usage pattern](https://github.com/filamentgroup/loadCSS#recommended-usage-pattern) and all suggestions I caught on issues. So:
1. As #180 and #183 I put CSS link tag before polyfill script
2. As #183 I have critical CSS in my head tag
4. It's not a problem of critical CSS as #199, indeed (as following)...

If I invert the order of loadCSS inclusion, first polyfill CSSrelpreload.js and after loadCSS.js magically it's all OK for Google Page Insight but in this case the preload doesn't work in Firefox and IE11.

So, I reverted to the same order specified in [loadCSS demo](http://filamentgroup.github.io/loadCSS/test/preload.html), first polyfill and and after loadCSS, but I got again warning from Google Page Insight.

How can I solve?

**Comment by scottjehl** [comment]
We've seen this issue for a while, and the PSI team has in the past acknowledged that the tool is imperfect at detecting whether some CSS blocks or not. I'd treat it as a tool for noting things you should look into further and verify yourself. 

If you can inspect your page and verify that your CSS file is loading asynchronously (the page should be able to render before the CSS arrives), then you should go good to go. WebPageTest.org is a great tool to test if assets block or not. I'd recommend it!
