### ISSUE TITLE
Preload polyfill needs CommonJS module wrapper

### ISSUE THREAD

**Issue by Kilbourne** [filamentgroup/loadCSS#201]
While loadCSS is requirable by building library , such Browserify and Webpack, the polyfill has no wrapper code. 
#171

**Comment by scottjehl** [comment]
For discussion, the script in question is here: https://github.com/filamentgroup/loadCSS/blob/master/src/cssrelpreload.js

**Comment by jhabdas** [comment]
@Kilbourne Have you considered shimming in your own wrapper?

**Comment by ryuran** [comment]
@jhabdas it's not really easy

**Comment by jhabdas** [comment]
Someone must've made a fork by now. What is preloaded CSS anyway? I've never heard of such a thing. In my websites I have:

- Inline CSS (sometimes critical)
- Async CSS using Fetch API (non-critical)
- Push State CSS (same as external)

**Comment by odahcam** [comment]
@jhabdas In this context, `preload` should means `async`. In HTML you need to use `<link rel="preload" />` for native async CSS loading support.

**Comment by jhabdas** [comment]
Ah. Preload related to Push State, yeah? I see support levels at ~50% with Safari [in hot persuit](http://caniuse.com/#search=Preload). Would preload then presumably be used for critical CSS not inclined in a document?

**Comment by rasenplanscher** [comment]
@Kilbourne What is the point, exactly?

If you `import 'fg-loadcss/dist/cssrelpreload';`, at least with webpack, you're good to go. Polyfills usually don't export stuff, by their very nature.

**Comment by rasenplanscher** [comment]
@scottjehl I think this is a `wontfix` and can be closed
