### ISSUE TITLE
loadCSS loads Google Web Fonts via URL

### ISSUE THREAD

**Issue by monolux** [filamentgroup/loadCSS#206]
Give this a try.

`loadCSS("https://fonts.googleapis.com/css?family=Roboto+Condensed:300,400,700");`

If I run this code after including loadCSS min js in the head the web font is loaded asynchronously, PageSpeed Insights also does not give a warning about blocking scripts or CSS.

If I load the link outside of loadCSS PageSpeed will complain naturally. I think since the source of the web fonts link is a CSS file this makes sense, meaning that loadCSS can handle direct Google Web Fonts links.

If this behaviour intended or is this how people could use loadCSS to asynchronously load web fonts?
Perhaps as a further alternative to [this](https://www.zachleat.com/web/comprehensive-webfonts/) list.

```
<!-- In functions.php -->

function styles_in_wp_foot() {

    // does not work guaranteed on all WP pages/categories/etc.
    // PageSpeed complains
    // echo '<script type="text/javascript">';
    // echo 'loadCSS("https://fonts.googleapis.com/css?family=Roboto+Condensed:300,400,700");';
    // echo '</script>';

    // PageSpeed complains, the fonts are render blocking.
    // echo '<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto+Condensed:300,400,700" type="text/css" media="all" />';    
}

add_action( 'wp_footer', 'styles_in_wp_foot' );


<!-- In header.php -->
<script>

//loadCSS
!function(a){"use strict";var b=function(b,c,d){function j(a){return e.body?a():void setTimeout(function(){j(a)})}function l(){f.addEventListener&&f.removeEventListener("load",l),f.media=d||"all"}var g,e=a.document,f=e.createElement("link");if(c)g=c;else{var h=(e.body||e.getElementsByTagName("head")[0]).childNodes;g=h[h.length-1]}var i=e.styleSheets;f.rel="stylesheet",f.href=b,f.media="only x",j(function(){g.parentNode.insertBefore(f,c?g:g.nextSibling)});var k=function(a){for(var b=f.href,c=i.length;c--;)if(i[c].href===b)return a();setTimeout(function(){k(a)})};return f.addEventListener&&f.addEventListener("load",l),f.onloadcssdefined=k,k(l),f};"undefined"!=typeof exports?exports.loadCSS=b:a.loadCSS=b}("undefined"!=typeof global?global:this);

// loads CSS asynchronously
loadCSS("<?php echo get_template_directory_uri(); ?>/style.min.css");
// loads Google Web Font asynchronously, PageSpeed Insights does not complain ;)
loadCSS("https://fonts.googleapis.com/css?family=Roboto+Condensed:300,400,700");

</script>
```
I am using above code in a WP theme and have outlined what did not work and what indeed did work with PageSpeed Insights, giving no warning about the web font. Unfortunately using something like `function styles_in_wp_foot()` and echoing loadCSS from there does not work, why I have no clue. So the only way to get PageSpeed to accept the web font being loaded asynchronously is to put it in the header.php directly.

Have been looking for a way to load Google Web Fonts asynchronously **without** actually using `@font-face` ([link](https://www.filamentgroup.com/lab/font-loading.html)) and [FontFaceObserver](https://helloanselm.com/2015/using-webfonts-in-2015/) **but** simply relying on `font-family: "Roboto Condensed", Helvetica, Arial, sans-serif;` for example.

For now I will stick to loading Google Web Fonts this way, **please** do let me know if this is **not** the intended use for loadCSS. Naturally I would be curious to read what you think about this approach, perhaps this is all just a bunch of rubbish from a beginner..

**Comment by MarcoHengstenberg** [comment]
@monolux Maybe these two articles by @zachleat will help you:

- https://www.zachleat.com/web/lazy-loading-webfonts/
- https://www.zachleat.com/web/comprehensive-webfonts/

**Comment by odahcam** [comment]
For loading fonts you should consider https://github.com/typekit/webfontloader

**Comment by zachleat** [comment]
Yeah, as @MarcoHengstenberg linked up on https://www.zachleat.com/web/lazy-loading-webfonts/ you’re asynchronously loading the CSS file, not the web fonts. The web fonts will still FOIT as normal with your loadCSS approach. Now, if the web fonts were inlined as Data URIs in the CSS, that would be a little different (see https://www.zachleat.com/web/comprehensive-webfonts/#async-data-uri)

Please reopen if you have additional questions!

**Comment by monolux** [comment]
@zachleat How did you make the [optimized lato](https://www.zachleat.com/web/css/fonts/lato/lato-zachleat-optimized.woff2)? Like [this](https://pixelambacht.nl/2016/font-awesome-fixed/)?

Is there a tool or package one could run over a font to just get the basic bits of the font, the _critical part of the font_ if you like, when wanting to use the [preload approach](https://www.zachleat.com/web/comprehensive-webfonts/#critical-foft-preload) with an optimized single web font alongside FontFaceObserver?

If there is not such a thing then [compressing fonts](https://github.com/bramstein/sfnt2woff-zopfli) is recommended, right?

Could [this](https://github.com/jhabdas/fetch-inject#use-cases) perhaps prove useful for font [loading](http://caniuse.com/#search=fetch)? Putting the FontFaceObserver script into that would only cause harm, right, meaning FontFaceObserver has to be inline to not cause render blocking?

Trying to learn and use a future friendly way/method with the current best practices and tools while showing the user no or minimal FOUT and FOIT.

Related, there is no closing `strong` tag [here](https://gist.github.com/zachleat/b651f6bdbc47c563affbfbed16d2d922/revisions?diff=split#diff-806b51b1316c48516276c1ce9bab65d4R107). Is that wanted?

**Comment by zachleat** [comment]
@monolux thanks for your comment!

> @zachleat How did you make the optimized lato? Like this?

Love that @roeln blog post, too! He actually helped me super-optimize the version of Lato that I have embedded in my first stage.

> Is there a tool or package one could run over a font to just get the basic bits of the font, the critical part of the font if you like, when wanting to use the preload approach with an optimized single web font alongside FontFaceObserver?

Have you seen https://github.com/filamentgroup/glyphhanger ? It might help you optimize your fonts. I put some installation instructions in the readme there to help get the proper dependencies installed.

> If there is not such a thing then compressing fonts is recommended, right?

The Glyphhanger readme has instructions on how to use pyftsubset to output WOFF2 compressed with zopfli.

> Could this perhaps prove useful for font loading? Putting the FontFaceObserver script into that would only cause harm, right, meaning FontFaceObserver has to be inline to not cause render blocking?

Just keep in mind that if you asynchronously load your CSS, it’s not the same as asynchronously loading the web font. Check this out: https://www.zachleat.com/web/lazy-loading-webfonts/

> Related, there is no closing strong tag here. Is that wanted?

Hmm, yeah there are a couple of those missing—I fixed them up, thanks!

**Comment by monolux** [comment]
@zachleat Thank you for your swift reply & help.

That glyphhanger sounds great already, will have a look right now alongside pyftsubset, thank you for the info.

Yes, won't be going down the lazy loading webfonts route due to FOIT occurring.

In order to get completely rid of FOUT and FOUIT, one _possible_ approach (is there a way actually?) I am thinking of not showing any font at the beginning and then fading in web fonts as they become available after loading them with a font loader. Good idea at all?

I am also thinking, for above the fold content use glyphhanger and pyftsubset alongside a font loader, show those ASAP via fade in when these critical/optimized font/glyphs are done loading and have below the fold showing text once the entire rest of the web font(s) finished loading, so later fade in. Possibly overkill though I am interested in the experience one could provide doing this. Have you tried something like that?

You wrote [fontfaceonload](https://github.com/zachleat/fontfaceonload) and there is [fontfaceobserver](https://github.com/bramstein/fontfaceobserver) as well as [webfontloader](https://github.com/typekit/webfontloader#events). Which one of the font loaders would best support having a `loading-fonts` event?

Yes webfontloader _has_ this already, though perhaps your lighter fontfaceonload or fontfaceobserver could be used and changed a bit to support the time from the request of the web font until it has finished loading?

Something like this?
```
var html = document.body.parentNode;

// if html tag does not have `fonts-loaded` class add it
// run this check every few milliseconds?
if (!(html.classList.contains('fonts-loaded'))){
  html.classList.add('fonts-loading');
}
else {
  html.classList.remove('fonts-loading');
}
```
That means I would have to check on the existence of the `fonts-loaded` class on the `html` tag every few milliseconds, (so do polling basically? - and that is generally not good advice I learned recently) or could this be done better? (I'll also try this [bare-bone approach](http://stackoverflow.com/a/11688948/1010918) and see where I get.)

Since I am beginner not seeing the closing tag did confuse me a bit, not nit-picking here but learning.

Find all this quite interesting and exciting, will make a few test-cases to compare, your feedback is invaluable, thank you (and I'll try hard to keep these message to a minimum size, thx 4 ur time)!

**Comment by zachleat** [comment]
I would discourage this approach. You want the text to be readable to a user as soon as possible, which means showing a fallback font while the web font is loading. There are techniques to reduce the reflow between your fallback font and web font. Check this out: https://meowni.ca/font-style-matcher/

Good luck!

**Comment by johanson** [comment]
@monolux You are over complicating things.
[fontfaceobserver](https://github.com/bramstein/fontfaceobserver) will return a Promise that resolves when the font is available.

`var lato = new FontFaceObserver('Lato');
lato.load().then(function () {
    document.documentElement.className += " fonts-loaded";
});`

**Comment by monolux** [comment]
@zachleat Keeping that in mind, thanks! Yes, seen font style matcher before, hmm so it really is about bringing text as soon as possible, meaning super fast.

I would image this so not to loose the [1000ms attention span](https://docs.google.com/document/d/1bYMyE6NdiAupuwl7pWQfB-vOZBPSsXCv57hljLDMV8E/edit) Google talks about. "A white screen during this is going to be jarring." [Ref.](https://www.paulirish.com/2015/advanced-performance-audits-with-devtools/) .. So no fading from white to site.. but the fading would indicate activity and create curiousness, similar to blur up technique used for images, no? Come on.. :(

Something like [this](http://gryphongroupe.com/), [this](https://macguruconsulting.com/) or [this](http://sosweetcreative.com/) is possibly asking too much waiting time from the user, right? Done properly it is what I am thinking of trying with web fonts.

@johanson Checked fontfaceobserver today and saw that also in [Edge](https://github.com/bramstein/fontfaceobserver/issues/97) it does not work, it is not adding the `fonts-loaded` class. Nonetheless I will give it and webfontloader a try.

**Comment by monolux** [comment]
For anyone interested and following this [here is a good write up](https://css-tricks.com/loading-web-fonts-with-the-web-font-loader/) on FOUT and FOIT and **why** one actually and still today **has** to choose between the two instead of trying to get rid of both. For me it was tough to understand that, besides using system fonts, there is no way of eliminating FOUT and FOIT altogether unless having the user experience suffer greatly.

Interestingly enough there is a comment about what I am trying to do, [fading fonts](https://css-tricks.com/loading-web-fonts-with-the-web-font-loader/#comment-1598212).

**Comment by zachleat** [comment]
Yes—Robin’s article is great!

But saying you have to choose between FOIT and FOUT is not quite true @monolux. If you want to eliminate both FOUT and FOIT, you can do that with an Inline Data URI approach:

https://www.zachleat.com/web/comprehensive-webfonts/#inline-data-uri

Not an ideal approach, but the option is there. I’d recommend reading that entire guide, if you get a chance. There are a couple of good approaches there to mitigate FOUT issues.
