### ISSUE TITLE
Call onload attribute handler

### ISSUE THREAD

**Issue by reepush** [filamentgroup/loadCSS#218]
I'm using `onload` attribute to detect when styles are loaded, so it's safe to init my scripts which uses dimensions. With Chrome everything is okey and my custom onload handler fires, but not with Safari. As I see Chrome supports `rel="preload"` attribute while Safari doesn't and polyfill doesn't trigger this handler.

Usage example:

```html
<link rel="preload" id="preload-stylesheet" href="styles.css" as="style" onload="window.app.stylesLoaded(event)">
```

What do you think about it?

**Comment by scottjehl** [comment]
I think this is covered in https://github.com/filamentgroup/loadCSS/pull/240. Can you confirm that it looks good to you? Thanks

**Comment by reepush** [comment]
@scottjehl yes, good work!
