### ISSUE TITLE
Append to body?

### ISSUE THREAD

**Issue by szepeviktor** [filamentgroup/loadCSS#224]
Hello!

```js
var refs = ( doc.body || doc.getElementsByTagName( "head" )[ 0 ] ).childNodes;
```
Does it mean that if `document.body` exists loadCSS will add the link element to it?

**Comment by scottjehl** [comment]
Yes. The aim is to load the stylesheet as late in the DOM as possible, unless there's an explicit placement specified.

**Comment by szepeviktor** [comment]
Thanks.

So you are adding the link element to `<body>`?

**Comment by scottjehl** [comment]
Yes, possibly. If you want a more specific place, you can specify one though.

More on stylesheets in body: https://jakearchibald.com/2016/link-in-body/

**Comment by szepeviktor** [comment]
Thank you very much for this blog post!
