### ISSUE TITLE
Version 1.3.1 not working with Webpack

### ISSUE THREAD

**Issue by kitajchuk** [filamentgroup/loadCSS#228]
The last stable version I have used with Webpack was v0.2.4.

However using the latest version, I get the following runtime error: `Uncaught TypeError: (0 , _fgLoadcss2.default) is not a function`.

It would appear the commonjs export is maybe incorrect. The latest version of loadCSS has this: `exports.loadCSS = loadCSS;`, which breaks on runtime with a Webpack bundle. If I change the line to this `module.exports = loadCSS;` in my compiled Webpack bundle and reload everything is solid.

**Comment by NekR** [comment]
Use `import { loadCSS } from 'fg-loadcss'`. Module uses what it uses, but you just should import it correctly.

**Comment by kitajchuk** [comment]
Ah, thanks @NekR . My bad :/

👍
