### ISSUE TITLE
Doesn't change media in Safari 10.0.3

### ISSUE THREAD

**Issue by JacobDB** [filamentgroup/loadCSS#229]
This script generally works great, but today I came across an odd issue in Safari 10.0.3 on macOS Sierra.

I see that a `<style>` is getting added just before each `<link>`, as it should, with `media` set to `only x`. Looking through the script, so far this is just fine. Where it breaks is it never changes the `media` back to `all` (or whatever I had it set to previously), it just stops at `only x`.

I did some debugging, and it appears that it sees my `modern.css` file just fine up until the point where it's supposed to swap the `media` value. I can't for the life of me figure out why.

This is occurring on the website linked below, but only on first page load (a cookie gets set so it just loads directly once cached), so you may need to check it in Incognito.

http://foxvalleyparkdistrict.org/

**Comment by JacobDB** [comment]
Quick update: I had to disable this stuff because the site is live, but if you need me to set up a test case, just let me know.

**Comment by scottjehl** [comment]
Is this still an issue you're experiencing? I could not reproduce it in Safari. I'll reopen if so, thanks!
