### ISSUE TITLE
Breaks Style on My Website

### ISSUE THREAD

**Issue by amiremami** [filamentgroup/loadCSS#230]
Hi :)

I guess the new version autoptimize use your method for it's critical css. Everything is fine on my website with autoptimize version 2.1.2 , but not with 2.2.0. 

When I update to that version my style breaks. The author of that plugin told me this is because of conflict between AO’s new way of doing inline & defer (using FilamentGroup’s loadCSS) and some other optimization component I'm using. 

But I'm not using another thing for my critical css, except the critical css has been hard coded into my header.

Do you have any idea why this happens?

THanks

**Comment by rasenplanscher** [comment]
@scottjehl 
Maybe close this? It's pre-v2, lacks detail, and is likely too old to be relevant. I looked into this for a few minutes: according to autoptimize, this is connected to Cloudflare Rocket Loader. I couldn't find out what version they are currently using, but v2 is probable.

**Comment by scottjehl** [comment]
Thank you @rasenplanscher. I agree it sounds like it'd be outdated by now. Happy to reopen if anyone still runs into this. More detail will be appreciated if so. Thanks!
