### ISSUE TITLE
Improvement for cssrelpreload.js (rel="preload" polyfill)

### ISSUE THREAD

**Issue by optimalisatie** [filamentgroup/loadCSS#231]
Hi!

Thanks a lot for providing a great function for async CSS loading!

I wanted to share a suggestion for an improved rel="preload" polyfill that will enable stylesheets to start loading async at the intended position in the HTML document.

```javascript
// if link[rel=preload] is not supported, we must fetch the CSS manually using loadCSS
if( !rp.support() ){ // ...

// start loading async as soon as stylesheet is added to DOM
document.addEventListener('DOMNodeInserted', function(MutationEvent) {
    if (typeof MutationEvent.target !== 'object') {
        return;
    }
    var el = MutationEvent.target;

    // rel="preload" stylesheet inserted in DOM, load async
    if (el.nodeType === 1 &&
        el.hasAttribute('as') &&
        el.hasAttribute('href') &&
        el.hasAttribute('rel') &&
        el.getAttribute('rel') === 'preload'
    ) {
        var href = el.getAttribute('href');
        if (!href) {
            return;
        }

        // load stylesheet async
        loadCSS(href, el, el.getAttribute('media'));
    }
}, false);
```

MutationObserver is advised as replacement for MutationEvents but it is much slower. As the polyfill is for old browsers, it may match the browsers that support `DOMNodeInserted`.

**Comment by scottjehl** [comment]
This is nice, thanks for the idea. We've been working on a refactor of cssrelpreload.js that reuses the existing link element in the page. In that refactor, loadCSS will no longer be called as a dependency, so the dom order concern here wouldn't apply. Would you be interested in looking it over and seeing what you think? https://github.com/filamentgroup/loadCSS/pull/240
Thanks again.
