### ISSUE TITLE
Publish minified files to NPM

### ISSUE THREAD

**Issue by erykpiast** [filamentgroup/loadCSS#232]
It'd be useful for folks (ex. me) who want to inline library and polyfil code. Until minified versions aren't part of NPM package I have to minify them by myself (which I want to avoid) or put those files to my repository, so I stop using NPM for managing version of this single dependency (which makes me sad and reminds me times when Backbone was the King and jQuery a Queen of JavaScript world).

**Comment by MarcoHengstenberg** [comment]
I'm in no way connected to Filament or this repo but from what I understand you could:

1. npm install loadCSS
2. import it into a javascript file of your liking
3. minify it during your build-process
(4. you may or may not want to concatenate the minfied script with others depending on a ton of factors)

If loadCSS indeed is your only dependency, then it sure might make sense to simply download it and keep an eye out for version updates (Watch the repository here).

**Comment by erykpiast** [comment]
Yeah, I know how to workaround, but I don't think it's the right way, to do workarounds. Many packages I use on daily basis distributes compiled/minified files along sources (I've never been caring about it, but apparently the day came) so I think it's perfectly possible to do it here as well.

For me, personally, this package is kind of special. It's not a part of my front-end codebase (so there is no minification/build process for it), but it's just read as a file and injected to HTML on backend side. That's why it's easier for me to keep the file in repository in old-fashioned way than create build pipeline especially for this package.

**Comment by scottjehl** [comment]
Thanks for commenting, folks. Good stuff all around. I think we can set up the releases so that the npm repository gets min files. I need to see how we've done that in other projects

**Comment by odahcam** [comment]
@erykpiast you could inject a minified version of the file, which would make your front-end code lighter.

**Comment by holtkamp** [comment]
Maybe the scripts part of this file can help as inspiration? 

https://github.com/longbill/jquery-date-range-picker/blob/master/gulpfile.js

**Comment by odahcam** [comment]
See #245

**Comment by scottjehl** [comment]
fixed in version 2.0.0-4. Please test if you can - we'll be rolling out 2.0.0 soon 👍
