### ISSUE TITLE
Register at CDN to increase ease of deployment

### ISSUE THREAD

**Issue by holtkamp** [filamentgroup/loadCSS#233]
To stimulate adoption and increase ease of deployment during production, registration of the dist (minified, related: https://github.com/filamentgroup/loadCSS/issues/232)  files at a CDN like http://www.cdnjs.com is useful.

Will try to submit it to http://www.cdnjs.com and report back here

**Comment by csswizardry** [comment]
Whilst not a _bad_ idea, I worry about putting critical (as in, on the critical path, as opposed to ‘important’) code on an external domain. The network overhead (DNS, TCP, TLS), particularly on high-latency connections, could introduce a slowdown greater than the one loadCSS is trying to mitigate.

It is in my opinion—and past experience—that critical resources such as these should be served from the host domain whose connection is already open. I’d be very interested in the discussion around this, though!

**Comment by evromalarkey** [comment]
It's now on jsdelivr or npm https://cdn.jsdelivr.net/npm/fg-loadcss@2.0.1/src/cssrelpreload.js

**Comment by odahcam** [comment]
All NPM packages are automatically included in some CDNs, like [UNPKG](https://unpkg.com/#/). 

**Example:**
 - https://unpkg.com/fg-loadcss@2.0.1/src/loadCSS.js 
 - https://unpkg.com/fg-loadcss

My opinion: this implementation shouldn't be a critical thing and if anyone wants to use the lib from a CDN this person can use, but also should know (maybe a note in the readme could do this) the colateral effects pointed by @csswizardry.

**Comment by evromalarkey** [comment]
yeah, I'm using it only to fetch it with php and inline as css (or you can http/2 push it), it's much easier to maintain versions this way.

**Comment by scottjehl** [comment]
Hi, thanks for the tip but we don't included minified files in the repo, and we generally don't recommend using a CDN for loadCSS, since we recommend inlining it in the page. (I understand some commenters include it server-side, which is great, but still). We'd recommend using the NPM package, Thanks!
