### ISSUE TITLE
“inlined or linked and http/2-pushed” …

### ISSUE THREAD

**Issue by fooness** [filamentgroup/loadCSS#235]
Dear community,

excuse me, if this is a strange question, but the README kind of confused me. Isn’t it possible to include loadCSS like this …

```
<link rel="stylesheet" type="text/css" href="/assets/css/index.css">
<link rel="preload" href="/assets/css/inject.css" as="style" onload='this.rel="stylesheet"'>
<script type="text/javascript" src="/assets/js/loadCSS.min.js"></script>
<script type="text/javascript" src="/assets/js/cssrelpreload.min.js"></script>
<script defer type="text/javascript" src="/assets/js/events.js"></script>
<title>TITLE</title>
```

… instead of inlining it, like the README explicitly states:

```
<link rel="preload" href="path/to/mystylesheet.css" as="style" onload="this.rel='stylesheet'">
<noscript><link rel="stylesheet" href="path/to/mystylesheet.css"></noscript>
<script>
/*! loadCSS. [c]2017 Filament Group, Inc. MIT License */
(function(){ ... }());
/*! loadCSS rel=preload polyfill. [c]2017 Filament Group, Inc. MIT License */
(function(){ ... }());
</script>
```

Thank you very much!

PS: Also I wondered, if it’s totally fine—also, like in the README—to link/inline the script AFTER the line with `rel="preload"` …

**Comment by scottjehl** [comment]
Hi there. 
Yes, you can reference loadCSS externally, and there are some situations where that is useful. However, in the example you've shown, the value of inlining any code (for both CSS and JS) is that it makes the code immediately available to execute when the HTML arrives. Files referenced externally, in contrast, introduce additional round trips to the server, which can add to the time it takes to display the page. Inlining of course conflicts with the goals of making external, cacheable files, so we'd typically only recommend doing it for small files and when the performance benefits are worth the tradeoff.

In modern server environments where http/2 is available, you can opt to try using server push to get the benefits of external referencing while still delivering files alongside the HTML as if they were inline. Doing this effectively can require a little bit of configuration on the server side, but we recommend this approach if you can do it. 

Thanks!
