### ISSUE TITLE
Firefox 56 issues

### ISSUE THREAD

**Issue by duply** [filamentgroup/loadCSS#237]
The latest Firefox 56 supports link preload now. However there do seem to be some issues when using it with loadCSS. I noticed that sometimes the rel attribute doesn't get updated from rel="preload" to rel="stylesheet" and thus the CSS will only be downloaded but not applied.

I'm able to reproduce the issue when I open https://master-origin-loadcss.fgview.com/test/preload.html
In Firefox 56 the page doesn't turn green. When I open the same link in Firefox 55 where the Polyfill is used it works just fine.

I assume that Firefox 56 doesn't fire the onload Event in some cases.

When I try the same code (just using absolute URL for the CSS) within jsfiddle it works just fine though.
https://jsfiddle.net/4mhg6p5h/

**Comment by MarcoHengstenberg** [comment]
Had the same problem (Firefox Nightly) today with local static HTML files.
As soon as I fired up the localhost and visited the static file it worked somehow.

Yet, this isn't a problem with loadCSS as far as I'm concerned as it also didn't work for Webfonts I was using preload for and referenced in my CSS.

So, my bet is, that this is most probably related to Firefox's implementation of preload.

**Comment by NeoGenet1c** [comment]
I'm having a very similar issue (FF56, Mac OS 10.12).

When I clear browser's cache and load all the page for the 'first time', the styles will not load. If I reload, the styles will load properly.

**Comment by duply** [comment]
Apparently Firefox currently only supports preload for cachable resources.
See: https://caniuse.com/#search=preload and https://bugzilla.mozilla.org/show_bug.cgi?id=1222633

I think the issues might be related to Firefox trying/failing to determine if the resource is cache-able due to slow response or the resource really not being cache-able.

If the resource is determined non-cacheable the onload callback is never fired. In case of loadCSS the rel="preload" will not be switched to "stylesheet".

If you implement the preload like suggested at https://developer.mozilla.org/en-US/docs/Web/HTML/Preloading_content you at least have the "regular" link element as fallback if the onload fails.

Maybe for loadCSS some similar fallback needs to be done in such cases? E.g. by adding the onerror trigger? So:
<link rel="preload" href="path/to/mystylesheet.css" as="style" onload="this.rel='stylesheet'"  onerror="this.rel='stylesheet'">

**Comment by NeoGenet1c** [comment]
@duply Very good idea, the `onerror` callback does work.

I think it's because the 'preload' is enabled in FF, so the execution of loadCSS is completely bypassed and FF triggers 'onerror' callback once it (incorrectly) fails to load the styles.

Not nice, but does do the job for me.

**Comment by scottjehl** [comment]
Couple updates here: first, from Mozilla:

> This feature was available in Firefox 56, but only for cacheable resources. It has been disabled in Firefox 57 because of various web compatibility issues (e.g. bug 1405761). An improved version that works for non-cacheable resources is expected to land in Firefox 58.

And second, to repeat above, if FF 56 deems a CSS file as non-cacheable, it will never fire the onload handler so the stylesheet will never be enabled. The ideal fix that will work right now is to set caching headers on the stylesheet so that Firefox deems it cacheable. Even a very short expiration appears to work. 

if you can't control the caching, the onerror solution could work temporarily, and there's not much of a downside since it's just toggling the rel attr to `stylesheet`, and that wouldn't do harm even if the `onerror` case happened to be legit for other reasons.
