### ISSUE TITLE
Improve Rel Preload Approach to be standalone

### ISSUE THREAD

**Issue by scottjehl** [filamentgroup/loadCSS#238]
The main priority of the loadCSS project is to provide a simple workflow around loading CSS with Rel=preload, so our existing cssrelpreload.js is in need of some updates.

1. The cssrelpreload.js file should not need to depend upon loadCSS or onloadCSS, as it can reuse and manipulate link elements that are already in the page.  This should simplify and lighten the scripting overall if you're only using loadCSS for a rel=preload helper.
2. It would be nice if we no longer use cookies and instead test alternative methods again, like localStorage, for flagging a stylesheet as already-in-cache

The work for this refactor is happening in the https://github.com/filamentgroup/loadCSS/tree/fall2017 branch

**Comment by MarcoHengstenberg** [comment]
Question: wouldn't it make more sense to use sessionStorage?

I can see the benefits of using localStorage (persistence) but the broader the approach is being used, the more information would end up in the localStorage, which shares the available space with the CacheStorage of ServiceWorker and sessionStorage and browser cache. Especially on devices where the available space for cachable data is low, this concerns me (only a little but yeah).
