### ISSUE TITLE
Distribute dist/ dir (minified files) with npm

### ISSUE THREAD

**Issue by nextgenthemes** [filamentgroup/loadCSS#245]
Seems the grunt uglify task is there but you never push those builds to github/npm. But to releases? I would not even know how I would do that.

**Comment by odahcam** [comment]
Add these files once for all, there's no good reason for not including them.

**Comment by odahcam** [comment]
See #232

**Comment by scottjehl** [comment]
fixed in master. thanks!

**Comment by scottjehl** [comment]
fixed in version 2.0.0-4 also, that is. 👍
