### ISSUE TITLE
Invalid "link" object in enableStylesheet

### ISSUE THREAD

**Issue by robertomatute** [filamentgroup/loadCSS#250]
Hi,

Thanks for this library.  Has been a great help for my project!

I have a problem with Firefox 57, and version 2.0.0-2 of `cssrelpreload.js`.

Muy page has many `<link..>` tags and the files get downloaded correctly, but never apply the style.  

Making some debug, I log  the function `enableStylesheet`:
```
        var enableStylesheet = function(whoami){
          link.media = finalMedia;
          console.log('enableStyleSheet==>', this.href);
        }
```  
And the link.href, is from other link object.  Not the one with the rel=preload attribute.

I changed to:
```
        var enableStylesheet = function(whoami){
          this.media = finalMedia;
          console.log('enableStyleSheet==>', this.href);
        }
```
(*this* instead of *link*)

And the style is applied correctly.  

Do you think i miss something? or could be variable `link` lost its reference in the callback?

Best Regard,

Roberto

**Comment by scottjehl** [comment]
Glad for pre-releases. I used `link` there to be able to reuse the function in both the event handlers and also the setTimeout, the latter of which has `this` referring to window. But you're right - the loop isn't going to enclose the variable scope as it is here. I'll fix it up and 2.0.0-3 up asap.

Thanks

**Comment by scottjehl** [comment]
@robertomatute if you get a chance, please let us know if 2.0.0-3 fixes this for you. Thanks for reporting!

**Comment by robertomatute** [comment]
@scottjehl I try the new version and everything work fine!

Thanks for your fast response!

Do you have any timeline for make 2.0.0 the latest release?

Best Regards
