### ISSUE TITLE
Minified cssrelpreload file hangs browsers that need the script

### ISSUE THREAD

**Issue by rsteinwand** [filamentgroup/loadCSS#251]
I'm having trouble with any minified version of the CssRelPreload. It works, but I get excessive cpu in IE and have to kill it. At least FF lets me close the tab. I'd link directly to the minified script, but content security policy blocks it.

Test page: https://www.intercepteft.com/test.html

Works fine in Chrome. Older version of LoadCss/cssRelPreload works fine.

**Comment by scottjehl** [comment]
Thanks for the report. Can you verify that the issue only exists with the minified version or is the issue present with either? Thanks again

**Comment by scottjehl** [comment]
Okay, verified that this is a bad bug. We see what it is now so we'll get a fix out asap and see what to do about hotfixing or patching. Thanks again.

**Comment by scottjehl** [comment]
Hi @rsteinwand 

We've made a patch prerelease and published it to 2.0.1-0. It seems to test well across all the IEs, Edge, Firefox, Safari, etc. We'll likely merge it right away here but if you get a chance, let us know if 2.0.1-0 fixes your issues.  Thanks

**Comment by rsteinwand** [comment]
Yes, much better. Problem resolved.

Thanks.
