### ISSUE TITLE
Strange behaviour in angular app on Edge 16

### ISSUE THREAD

**Issue by manzonif** [filamentgroup/loadCSS#255]
When I use it on Edge, the onload handler never stop to be called.
I need to remove from my link:
`onload="this.onload=null;this.rel='stylesheet'"`

or add "link.onload = null;" in source code, before addEventListener:

```
// bind load handlers to enable media
link.onload = null;
if( link.addEventListener ){
```

**Comment by mikeytown2** [comment]
Also happens with IE11 on windows 7

**Comment by rasenplanscher** [comment]
@scottjehl Maybe close this as obsolete?
This is old, the posted code does not seem to indicate a problem with `loadCSS` as per the current docs, and Edge is at version 44 by now.

**Comment by scottjehl** [comment]
Since the readme recommends setting it to null and the script does so too as backup. I think we're good now yes. Thanks.
