### ISSUE TITLE
seo seems to load twice with cssrelpreload

### ISSUE THREAD

**Issue by u007** [filamentgroup/loadCSS#256]
ive tested a site on:
https://developers.google.com/speed/pagespeed/insights

and it seems to show css being loaded twice
https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fnurture.ai

**Comment by u007** [comment]
but works great on browser

**Comment by JMPerez** [comment]
@u007 I'm checking and you are right. On the browser and [webpagetest](https://www.webpagetest.org/result/180108_YQ_25b900751e108cc641d9bc06c80bab53/1/details/#waterfall_view_step1) the CSS is only requested once.

I'm not sure if this issue should be kept open, as it seems to be something on pagespeed's side.

**Comment by u007** [comment]
nice :),

thanks for checking it out, yes i suspect its google pagespeed issue.
i feel the site is fast enough, but somehow it still complaints on pagespeed

**Comment by JMPerez** [comment]
It also happens with `https://fonts.googleapis.com/css?family=Open+Sans:300,400,600`. It actually shows it 3 times.

<img width="959" alt="screen shot 2018-01-08 at 16 00 52" src="https://user-images.githubusercontent.com/416456/34676490-43c4e362-f48d-11e7-8639-3e2c3ac19837.png">

I tried with [the demo page](https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fmaster-origin-loadcss.fgview.com%2Ftest%2Fpreload.html&tab=mobile) but it doesn't show that section, probably because it needs to request more CSS resources to show up.

**Comment by rasenplanscher** [comment]
@u007 @JMPerez 
Can you verify please? As far as I can tell, the issue does not show up anymore.

**Comment by JMPerez** [comment]
@rasenplanscher It doesn't happen anymore. However, I just browses the initial payload for nurture.ai and can't see the ` loadCSS` function anymore. 

I know https://www.smashingmagazine.com/ uses a similar function and PageSpeed Insights doesn't report render-blocking issues on that site.

**Comment by rasenplanscher** [comment]
@JMPerez
Thank you for checking again 😄 

> It doesn't happen anymore. However, I just browses the initial payload for nurture.ai and can't see the ` loadCSS` function anymore.

They have it in their `application.[hash].js`.


> I know https://www.smashingmagazine.com/ uses a similar function and PageSpeed Insights doesn't report render-blocking issues on that site.

They use this package, this is copied verbatim from their homepage:
```
<script>
   
  (function(w){"use strict";var loadCSS=function(href,before,media){var doc=w.document;var ss=doc.createElement("link");var newMedia=media||"all";var ref;if(before){ref=before}else{var refs=(doc.body||doc.getElementsByTagName("head")[0]).childNodes;ref=refs[refs.length-1]}var sheets=doc.styleSheets;ss.rel="stylesheet";ss.href=href;ss.media="only x";function ready(cb){if(doc.body){return cb()}setTimeout(function(){ready(cb)})}ready(function(){ref.parentNode.insertBefore(ss,before?ref:ref.nextSibling)});var onloadcssdefined=function(cb){var resolvedHref=ss.href;var i=sheets.length;while(i--){if(sheets[i].href===resolvedHref){return cb()}}setTimeout(function(){onloadcssdefined(cb)})};if(ss.addEventListener){ss.addEventListener("load",function(){this.media=newMedia})}ss.onloadcssdefined=onloadcssdefined;onloadcssdefined(function(){if(ss.media!==newMedia){ss.media=newMedia}});return ss};if(typeof exports!=="undefined"){exports.loadCSS=loadCSS}else{w.loadCSS=loadCSS}})(typeof global!=="undefined"?global:this);
  loadCSS('/css/main.css');
</script>
```



@u007 @scottjehl 
Please close this issue, it seems to be resolved.
