### ISSUE TITLE
Minified files not on github (dist folder). Workarround.

### ISSUE THREAD

**Issue by nextgenthemes** [filamentgroup/loadCSS#258]
Its pretty common that packages have the dist folder with minified filed on Github. For this project they are only on NPM but not here.

If you like me just want to copy paste the relpreload js to inline it you can get the latest this way without any npm or other stuff.

https://cdn.jsdelivr.net/npm/fg-loadcss@latest/dist/cssrelpreload.min.js

**Comment by j-pinder** [comment]
The minified file returns an error in the console "!undefined is not an object(evaluating t.loadcss). The CSS fails to load in Safari, where JS is enabled.

I've minified the code with Codekit and [Javascript Minifier](https://javascript-minifier.com)online. I've also linked to this CDN link, which the minified code is the same as what I've created from the above-mentioned and also has an error.

I'm trying to find a way to minify the file while maintaining functionality. If it has worked for you, can you advise, and maybe assist in pointing out what might be the cause.

**Comment by scottjehl** [comment]
Thanks for the suggestion. We don't include minified files in our source repos, but we appreciate the idea, thanks.
