### ISSUE TITLE
Firefox Bug - Crash issues with Version <= 41 and loadCSS v2.0.1

### ISSUE THREAD

**Issue by duply** [filamentgroup/loadCSS#261]
Hi,

I recently updated to loadCSS v.2.0.1 and noticed that older Firefox Versions completely crash the Browser on pageload.
Using Browserstack I narrowed it down to Firefox 41 and below. Not exactly sure what's causing this. Reverting back to loadCSS v1.3.1 resolved the issue though.

I can reproduce the error using the demo page and Firefox 41:
https://master-origin-loadcss.fgview.com/test/preload.html

**Comment by gaaarg** [comment]
Hello,

Any updates about this issue ?
Is it something the filamentgroup will plan to fix?

**Comment by rsteinwand** [comment]
I can confirm it's a problem for my website as well.

But I have no clue if any of our customers use FF 41.

**Comment by ryantoft-gm** [comment]
Usage on FF 41 and earlier is going to be low. But the fact that it crashes the whole browser is pretty rough.

For what it's worth it looks like the issue was introduced in this commit - likely related to the way the load handlers were changed: https://github.com/filamentgroup/loadCSS/commit/afa545b4a0c11bf1b9711b563c7422dfffb74724

**Comment by scottjehl** [comment]
good to know thanks!

**Comment by gaaarg** [comment]
FYI
It was said in the #262  discussion that the `onload="this.onload=null;this.rel='stylesheet'"` resolve also this issue. I test it and it works fine in FF 41. 

So it seems that using the last version commited (but not tagged) of loadCSS fix this.
https://github.com/filamentgroup/loadCSS/blob/918a3318f055002b4bee729840e420e057637c7a/src/cssrelpreload.js

Any reason why this commit has not been tagged ?

**Comment by rasenplanscher** [comment]
@scottjehl Can this be closed? The commit in question should be in the 2.1.0 release.

Maybe @duply or @rsteinwand can confirm it's fixed?

**Comment by gaaarg** [comment]
@rasenplanscher we update to v 2.1.0 and seems to works fine in FF41 & IE 11
