### ISSUE TITLE
Load multiple CSS files - part 2

### ISSUE THREAD

**Issue by ghost** [filamentgroup/loadCSS#263]
With reference to this post... [https://github.com/filamentgroup/loadCSS/issues/77](url)

Any hints how this combine, minify and one function call, can be done... ? I have following code I am struggling with...

```
< link rel = "preload"
href = "STYLE_ONE"
as = "style"
onload = "this.onload=null;this.rel='stylesheet'" >
	<
	noscript > < link rel = "stylesheet"
href = "STYLE_ONE" > < /noscript> <
	link rel = "preload"
href = "STYLE_TWO"
as = "style"
onload = "this.onload=null;this.rel='stylesheet'" >
	<
	noscript > < link rel = "stylesheet"
href = "STYLE_THREE" > < /noscript> <
	link rel = "preload"
href = "STYLE_THREE"
as = "style"
onload = "this.onload=null;this.rel='stylesheet'" >
	<
	noscript > < link rel = "stylesheet"
href = "/style.css" > < /noscript> <
	script >
	/*! loadCSS rel=preload polyfill. [c]2017 Filament Group, Inc. MIT License */
	(function () { ...
	}()); <
/script>
```

**Comment by rsteinwand** [comment]
Easy: Combine your 3 stylesheets into one file. Use LoadCSS code to load your only file. 
Done.

This is not an issue that LoadCSS devs need to fix.

**Comment by rabas007** [comment]
@rsteinwand - all files are external files on a CDN. So how?

**Comment by johanson** [comment]
What is the point of using this library then?

**Comment by scottjehl** [comment]
Hey folks. @rabas007 Would you mind rephrasing the question? I'm not sure I understand the issue you're running into. Thanks

**Comment by rsteinwand** [comment]
rabas007: loadCSS is designed to help load CSS files _**that are not critical**_ to the initial rendering of the page, and instead desirable to load in an asynchronous manner. (For including critical CSS in a page without blocking rendering, we recommend either inlining that CSS in a style element, or referencing it externally and server-pushing it using http/2.)

**Comment by scottjehl** [comment]
Sounds like this issue was worked out in the comments. I'll close it but feel free to ask again if you need anything
