### ISSUE TITLE
Filament example webpage not passing the Chrome Lighthouse Audit test for Critical Request Chains

### ISSUE THREAD

**Issue by world33** [filamentgroup/loadCSS#264]
Can anybody please explain why the Filament Group example page for loadCSS at 
https://master-origin-loadcss.fgview.com/test/preload.html
is not passing the **Chrome Lighthouse Audit Test**?

![lighthouseaudit](https://user-images.githubusercontent.com/20501877/36340942-b16df580-143a-11e8-918c-87a6402d65e5.png)

and the slow.css.php file is shown as blocking the rendering of the page?

Anything to do with the fact that Chrome Lighthouse is using the Nexus 5 device to audit webpages?
I am puzzled. Thanks for any help.

**Comment by futtta** [comment]
to quote from a response in another issue:
> loadCSS is designed to help load CSS files that are not critical to the initial rendering of the page, and instead desirable to load in an asynchronous manner.

The green background very likely is considered critical by Chrome Lighthouse and hence the (final) rendering of the page requires the (slow loading) CSS-file. You would typically add "critical CSS" inline to allow the rendering of the (above the fold part of the) page to fix this.

**Comment by scottjehl** [comment]
Great point, @futtta. I bet you're right about that. I wonder if we should change the demo page to avoid a more major design shift...

**Comment by scottjehl** [comment]
Note: this issue appears even if loadCSS is not in the page at all. I've filed an issue here, but it's more about Lighthouse and `onload=this.rel=stylesheet` than anything this script is doing, since Chrome supports it natively.  

https://github.com/GoogleChrome/lighthouse/issues/4702
