### ISSUE TITLE
Onload event never fires in Firefox59

### ISSUE THREAD

**Issue by MarcoHengstenberg** [filamentgroup/loadCSS#271]
I can recreate the behaviour by visiting your demo page: https://master-origin-loadcss.fgview.com/test/preload.html

The onload event never fires and thus the rel-values remains at `preload`. I never get to see the green background with white text. :(

**Comment by scottjehl** [comment]
Hmm. I can't seem to reproduce this in Firefox 59 here. Loads as expected for me with the link above.

**Comment by futtta** [comment]
Tested w. FF 59.0.2 on Ubuntu, but cannot reproduce either.

**Comment by zachleat** [comment]
works for me on 59.0.1 Mac OS (Low) Sierra

**Comment by MarcoHengstenberg** [comment]
I set “Network.Preload” in my Firefox about:config to true/enabled. -.- Somehow this prevented stylesheets from the same source to fire an onload event.
Sorry for the fuzz.
Now, after re-setting it to false/disabled all works as expected.

**Comment by ensemblebd** [comment]
```
<footer>
<script type="text/javascript' async="false" defer="defer">
	      function supportsToken(token) {return function(relList){
			if (typeof(relList)!=='undefined' relList.supports && token) return relList.supports(token);
			return false;
		}};
		var supportsPreload = supportsToken("preload");
		var rl = document.createElement("link").relList;
		if (!supportsPreload(rl)) {
			var cb=function(link) {link.onload=null; link.rel='stylesheet';};
			var targets = document.querySelectorAll('link[rel=preload]');
			for (var i=0; i<targets.length;i++) cb(targets[i]); // ie support, re: forEach.
		}
</script>
</footer>
```
