### ISSUE TITLE
Chrome warning: "link preload .. make sure it has an appropriate `as` value .."

### ISSUE THREAD

**Issue by caub** [filamentgroup/loadCSS#272]
I get this warning
```
The resource http://fonts.googleapis.com/css?family=Roboto:300,400,500 was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it Please make sure it has an appropriate `as` value and it is preloaded intentionally.

```

code: 

```js
const last = document.head.childNodes[document.head.childNodes.length - 1];
loadCSS('https://fonts.googleapis.com/icon?family=Material+Icons', last); 
```
<sub>note: would be great to have an option to make the above simpler</sub>

**Comment by MatTeague** [comment]
I'm getting the same warning when using the '_How To Use loadCSS (Recommended example)_' . So I would also like to know the answer to this.

**Comment by rasenplanscher** [comment]
@caub 
The warning indicates `http://fonts.googleapis.com/css?family=Roboto:300,400,500`, while your code sample requires `https://fonts.googleapis.com/icon?family=Material+Icons`. Are you sure, you don't have another `<link rel="preload" ...` tag somewhere on your page? Can you reproduce the issue in a codepen?

> note: would be great to have an option to make the above simpler
Care to elaborate? What do you envision?

**Comment by rasenplanscher** [comment]
@MatTeague 
Can you share your setup code?

**Comment by caub** [comment]
@rasenplanscher seems you're right, the warning was from another asset, not loaded with loadCSS https://codesandbox.io/s/4w6n35jjjw

my note concerns the API, it's pretty hard to insert the CSS at the end of the document head for example
Something like:  a `loadCSS(url, container, mode)` would be useful
```js
loadCSS('https://fonts.googleapis.com/icon?family=Material+Icons', document.head, 'append');
```
where mode would be append/prepend/before/after, default to after

**Comment by scottjehl** [comment]
@caub I think the `before` argument should do what you're looking for? 

From the readme: 

> before: By default, loadCSS attempts to inject the stylesheet link after all CSS and JS in the page. However, if you desire a more specific location in your document, such as before a particular stylesheet link, you can use the before argument to specify a particular element to use as an insertion point. Your stylesheet will be inserted before the element you specify. For example, here's how that can be done by simply applying an id attribute to your script.

https://github.com/filamentgroup/loadCSS#function-api

**Comment by scottjehl** [comment]
Hmm, actually after a second read it looks like you were already using that. Sorry!

**Comment by rasenplanscher** [comment]
@caub 
Please, have a look at #298 
I think that should do it now 👍 
Let me know what you think

**Comment by caub** [comment]
`options.appendTo` is great, thanks
