### ISSUE TITLE
Please, what's wrong.

### ISSUE THREAD

**Issue by MarcelVe** [filamentgroup/loadCSS#273]
Hi, I need some help.

In this situation below, loadCSS is not working. Can you please tell me why?
https://developers.google.com/speed/pagespeed/insights/?hl=en&url=http%3A%2F%2Fwww.iluctron.com.br%2Fempresa%2Filuctron-fabrica-leds-para-iluminacao-residencial-comercial-industrial%2F&tab=desktop

Thank you so much.

**Comment by rsteinwand** [comment]
What makes you think it's not working? 

There are minor, unresolved issues with Pagespeed Insights and LoadCSS.

**Comment by scottjehl** [comment]
PSI has updated recently to run on lighthouse. i think you'll find its recommendations have improved. Thanks
