### ISSUE TITLE
Font-display breaking rel=preload on IOS safari

### ISSUE THREAD

**Issue by leonmondria** [filamentgroup/loadCSS#274]
Heads up!

When using:
`<link rel="preload" href="x.css" as="style" onload="this.onload = null;this.rel='stylesheet'" />`

`@font-face {
    font-family: "Droid Sans";
    src: url("/content/font/DroidSans-Bold.woff");
    font-weight: bold;
    font-style: normal;
    font-display: swap;
}`

If you have font-face declarations with **font-display: swap;**, IOS safari doesn't set the rel attribute so no stylesheet will be applied. 

I have this issue with IOS 11.3, can anyone confirm?

**Comment by leonmondria** [comment]
This apprears to be fixed in Safari release 53:

https://developer.apple.com/safari/technology-preview/release-notes/:
**Fixed loading the stylesheet when changing the <link> element rel attribute from preload to stylesheet**

**Comment by leonmondria** [comment]
The demo works like a charm, seems that the combination preload + swap is 'fatal' on iphone 6 + ios 11.3. 
If the stylesheet is included with <link rel=stylesheet /> it does work (GO APPLE).

If you run the css through https://jigsaw.w3.org/css-validator/ that will also fail so maybe the swapping does some sort of validation in that IOS/iphone combo?

Anyway, now it's a known problem so if i get customer questions, i tell them to update their phone.

**Comment by scottjehl** [comment]
Sounds like this one is worked out now, so I'll close but feel free to comment if it's still unresolved.
