### ISSUE TITLE
Docs state that onload event support for link elements is spotty. Is it the same for the polyfill?

### ISSUE THREAD

**Issue by fedeTibaldo** [filamentgroup/loadCSS#276]
Hi everyone. I was reading the docs when I stumbled upon this phrase ([Using with onload](https://github.com/filamentgroup/loadCSS/blob/master/README.md#using-with-onload) paragraph):

> Onload event support for `link` elements is spotty in some browsers, so if you need to add an onload callback, include [`onloadCSS` function](https://github.com/filamentgroup/loadCSS/blob/master/src/onloadCSS.js) on your page and use the `onloadCSS` function

It really caught my eye, mainly because it made me wonder whether there is any difference, in term of reliability, between the `loadCSS` script and the polyfill.

I want to keep my page light. For this reason, I always include only the latter. At the same time, `onload` events are crucial to my webpage rendering, so I can't just trust them, I must be sure of them.

Is there any irregular browser when it comes to the polyfill or is it just a `loadCSS` thing? If the former is true, is `onloadCSS` the only solution?

**Comment by scottjehl** [comment]
Great question. Sorry for the long delay, we're doing triage in here now. Good news is you don't need the onloadcss.js script: the preload polyfill has a 3 second fallback to apply the stylesheet https://github.com/filamentgroup/loadCSS/blob/master/src/cssrelpreload.js#L59

thanks!
