### ISSUE TITLE
Relative paths do not work

### ISSUE THREAD

**Issue by machal** [filamentgroup/loadCSS#29]
```
loadCSS("../dist/css/style.css");
```

If I'm calling loadCSS this way, it does not work. The problem is IMHO on [line 29](https://github.com/filamentgroup/loadCSS/blob/master/loadCSS.js#L29). 

loadCSS does not found relatively called stylesheet and `media` attribute is remaining on `only x` value.

On my project I can fix it easily, but maybe someone will experience the same problem.

**Comment by zachleat** [comment]
Fixed by #32
