### ISSUE TITLE
Any perf. savings by putting CSS link(s) at the bottom?

### ISSUE THREAD

**Issue by kevinSuttle** [filamentgroup/loadCSS#30]
Depending on the size of one's CSS, this could exacerbate the FOUT, but I'd love to see some metrics on non-JS solutions, or at least solutions not initially requiring JS. 

For example, how much perf cost could one save by: 
* inlining critical CSS at the top of the page 
* putting the CSS file link at the bottom of the page to avoid blocking
* progressively enhancing to be async

@scottjehl's comments so far:

> You could! JS can make the async request sooner tho. We also set a cookie once we request it (so we can assume it's in cache)

> we typically have a link to the full css in a noscript, but the JS probably could reuse that reference, I guess

> we tend to define our urls in meta tags now, but there's an overlap there in the fallback css link, if that's what you mean

**Comment by Ianfeather** [comment]
> putting the CSS file link at the bottom of the page to avoid blocking

This is likely to be a little unpredictable. The browser is going to do a look-ahead and block render as soon as it spots a css link. I've seen quite large performance hits when trying it out myself where the user sees a frozen, semi-rendered page until the last request finishes.

Behaviour of the "browser" I mentioned there is likely to be widely variable so you might see good results somewhere. I think this solutions depends on the resource priorities spec landing before you could rely on it consistently.

**Comment by kevinSuttle** [comment]
Very good point. Thanks @Ianfeather.

**Comment by jakearchibald** [comment]
You could put the CSS in the head but with `media="only x"`. That'll stop the blocking, but you'll still need JS to switch it to `all`.

**Comment by scottjehl** [comment]
Good points, thanks everyone. 

Indeed, I've seen stylesheet `links` at the end of the `body` block render just like they do from the `head`. My assumption is that it's more about the timing of the request going out than where it happens to be in the source order.

And agreed: the `only x` trick is basically what loadCSS does internally, so you could toggle an existing link if you prefer. loadCSS might be more convenient but it's up to you.

I do wish we had an `async` attr for CSS. But even in the case of `script`, where we do have `async` and `defer` availabile, I find it's often very useful to use a script loader anyway to qualify the conditions at which the request is made in the first place (based on feature support and other conditions).

Anyway! I'm going to close this out. Thanks.

**Comment by kevinSuttle** [comment]
Thanks @scottjehl, @jakearchibald.
