### ISSUE TITLE
Error thrown by Content-Security-Policy

### ISSUE THREAD

**Issue by dracos** [filamentgroup/loadCSS#308]
The following line:
https://github.com/filamentgroup/loadCSS/blob/32f6847ca1d506456bf15e4b0e008a4abebcdba4/src/cssrelpreload.js#L42
causes an error in e.g. Firefox when a CSP header banning inline script is in operation: "Content Security Policy: The page's settings blocked the loading of a resource at inline ("script-src")."
Now I'm not sure if this is a bug in Firefox or not - should it throw a CSP violation when an attribute is only being set to null? - but I wondered if `removeAttribute` could be used instead, which does not cause a violation. Not sure if that has any issues, I couldn't see anything in the repo as to why setAttribute was used.

**Comment by dracos** [comment]
Hmm, https://developer.mozilla.org/en-US/docs/Web/API/Element/setAttribute actually says:
> Since the specified value gets converted into a string, specifying null doesn't necessarily do what you expect. Instead of removing the attribute or setting its value to be null, it instead sets the attribute's value to the string "null". If you wish to remove an attribute, call removeAttribute().
So perhaps setting it to `null` is not the right thing to do, and the bug is here, not Firefox.

**Comment by gr8bit** [comment]
Your CSP seems to forbid the execution of inlined javascript. Therefore you won't be able to execute ANY javascript that's in the HTML of the page, be it between <script> tags or in an element's attribute (e.g. "onload").

**Comment by dracos** [comment]
You can run inline javascript within a <script> tag if you provide a nonce. Which is what I was doing, which is what led to me opening this ticket.

**Comment by gr8bit** [comment]
Oh, I overlooked that the source is actually in loadCSS, my bad. Did you (or Firefox) solve it in the meantime?

**Comment by dracos** [comment]
No, I still get the CSP error in Firefox running that line (you can see it on https://www.fixmystreet.com/ for example). I should probably switch to the removeAttribute thing I suggest here, I guess I thought it would get merged by now.
