### ISSUE TITLE
The plugin doesn't do anything to preload elements in Firefox

### ISSUE THREAD

**Issue by GalaxySH** [filamentgroup/loadCSS#314]
Current Example: https://hauge.rocks

When I visit the page, the plugin (which works on Opera, Safari, Chrome, and Edge for the site) doesn't change the value of `rel=preload` to `rel=stylesheet`. Literally nothing happens. The `onload="this.onload=null;this.rel=stylesheet"` values in the stylesheet link are still there like nothing happened.

**Comment by scottjehl** [comment]
Try this pattern, it's better for a lot of reasons:
`<link rel="stylesheet" href="/path/to/my.css" media="print" onload="this.media='all'">`

https://www.filamentgroup.com/lab/load-css-simpler/
