### ISSUE TITLE
Cannot install version 3.0.0 because node version is hardcoded to 11.9.0

### ISSUE THREAD

**Issue by gr8bit** [filamentgroup/loadCSS#316]
Attempting to update gives me the following error on yarn install:

error fg-loadcss@3.0.0: The engine "node" is incompatible with this module. Expected version "11.9.0". Got "12.16.1"

Previous version 2.1.0 didn't require the engine version. How can I fix this? Thanks a lot in advance!

**Comment by eshimischi** [comment]
Yeah! Just wanted to start the same issue, but saw one is here already. I use Node 12.16.2 but library is stuck to 11.9.0

**Comment by gr8bit** [comment]
@scottjehl is probably the man who can shed some light on our darkness here ;)

**Comment by gr8bit** [comment]
@eshimischi for the moment, you can add
`    "fg-loadcss": "bichinger/loadCSS#extend-engine-requirement",`
to your package.json (which is the above mentioned PR #317 ).

**Comment by scottjehl** [comment]
@gr8bit thank you. merging your PR for a release this morning.

**Comment by psdon** [comment]
Hope this fix soon. I encounter the same issue
