### ISSUE TITLE
Where has the cssrelpreload polyfill gone in 3.0.0?

### ISSUE THREAD

**Issue by gr8bit** [filamentgroup/loadCSS#318]
It vanished from source and documentation... can somebody explain why? I used to include that in my JS...

**Comment by scottjehl** [comment]
Hi there, 

I'm sorry that I didn't make this clearer in the release notes. It's hopefully clear in the readme now.
 
I made a major version bump in efforts to prevent auto-upgrades to this version that deprecates that preload pattern. For continued compatibility with the preload pattern, you can stick to version 2.1.0 or prior, which will remain on NPM.

Here's some more info on the change https://github.com/filamentgroup/loadCSS/blob/master/README.md#changes-in-version-30-no-more-preload-polyfill

Thanks and sorry for the mixup on my part

**Comment by gr8bit** [comment]
Aaah now I get it. I'd rather switch to 3.0.0. Thank you!
