### ISSUE TITLE
Why do I sometimes get a recommendation in google pagespeed 'Reduce unused CSS' ?

### ISSUE THREAD

**Issue by SergeyKhlopov** [filamentgroup/loadCSS#333]
Hello, please tell me.
I do optimization on one site, embed the critical css in `<style>...</style>`,
then connect the non-critical css like this: `<link href="home.css" media="print" onload="this.media='all'; this.onload=null;" rel="stylesheet">`.
But Google Pagespeed sometimes has a recommendation "Reduce unused CSS" and points to a file home.css.
But the home.css file is connected asynchronously, why does this recommendation appear and how to fix it ?

And is it right to do so that each page has its own css file?
On the main page - home.css
On the product page - product.css
On the page contacts - contact.css

Thank you in advance for your response =)

**Comment by WraithKenny** [comment]
I was confused about this too. I think the lighthouse message is confusing. The "async" is working, and it still complains about unused styles.

"Reduce unused CCS" and "Eliminate render-blocking resources" are two different items. You're files should only be showing up in one.
