### ISSUE TITLE
Wouldn't loading css asynchronously cause FOUC?

### ISSUE THREAD

**Issue by littlee** [filamentgroup/loadCSS#334]
After I read this blog recently https://www.filamentgroup.com/lab/load-css-simpler/

I'm confused, will this code below cause FOUC

```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <link rel="stylesheet" href="./some-large-file.css" media="print" onload="this.media = 'all'">
</head>
<body>
  <h1>AAA</h1>
</body>
</html>
```

in what situation would we prefer to load css asynchronously?

**Comment by scottjehl** [comment]
> I'm confused, will this code below cause FOUC

That's correct. You would want to use async CSS loading for low-priority stylesheets that aren't critical to the initial page rendering. The CSS file for google fonts is [one example where people have used this](https://csswizardry.com/2020/05/the-fastest-google-fonts/). Or, the styles for a chat or reviews widget that are shown after user input could be a candidate for async loading. Additionally, [some sites inline their most important CSS and async-load the rest](https://web.dev/extract-critical-css/), broken apart by which styles are used in the first visible sections of a page.
