### ISSUE TITLE
Chrome console error : Unhandled promise rejection

### ISSUE THREAD

**Issue by russellgoldenberg** [filamentgroup/loadCSS#35]
Chrome Version 40.0.2214.111 (64-bit)
This doesn't show up in Firefox or Safari. Occurs in my local dev setup and on your [demo site](http://master.origin.font-loading.fgtest.com/data-uris.html).

**Comment by zachleat** [comment]
Just as information, this is not a loadCSS issue. This is https://github.com/filamentgroup/woff2-feature-test/issues/4

Thanks, we’ll get the demo site updated!

**Comment by zachleat** [comment]
Demo site updated! Thanks!
