### ISSUE TITLE
Pass in optional arguments as options object

### ISSUE THREAD

**Issue by matijs** [filamentgroup/loadCSS#38]
How do you feel about passing in the optional arguments as an options object.
```javascript
loadCSS('path/to/styles.css', {
  'before': document.getElementsByTagName('script')[0],
  'media': 'all',
  'callback': function() {
    // magic
  }
}
````
It's a little cleaner when, for example, you only want to use a callback and not toch the `before` and `after` arguments.

**Comment by scottjehl** [comment]
I agree that this would be better. I'm not sure that I agree it's worth breaking compatibility for it, unless we needed to add yet another argument anyway. Thoughts?

**Comment by scottjehl** [comment]
Closing out but open to further discussion. Thanks.
