### ISSUE TITLE
Double callback with onload

### ISSUE THREAD

**Issue by zachleat** [filamentgroup/loadCSS#41]
Firefox triggers an onload callback twice when the media attribute is changed before load succeeds.

This does not happen when the `ss.media = media || "all";` line is commented out. It does happen even if the media value doesn’t change (for example changing the initial `ss.media = "only x";` to `ss.media = "all";`)

This is probably something we should file upstream at Mozilla’s tracker.

Update: also happens in newest Chrome, Safari 8.0.3 and I’m assuming others.

Test url: http://filamentgroup.github.io/loadCSS/test-callback.html

**Comment by zachleat** [comment]
Of note: even without an onload callback, there are duplicate requests happening in Chrome (not Firefox or Safari)

Test url: http://filamentgroup.github.io/loadCSS/test.html

**Comment by zachleat** [comment]
TODO: make sure what’s in github pages matches what’s on the master branch. I didn’t test to see if they were different.

**Comment by scottjehl** [comment]
confirmed. that sure seems browser-buggy to me. It even says the source of the second request is the toggle media function, which does nothing but just that...

![image](https://cloud.githubusercontent.com/assets/214783/6363633/48718102-bc61-11e4-8c0d-8d4768ba41e7.png)

**Comment by scottjehl** [comment]
I added gh-pages recently to run the test/ files for another issue, that’s all it’s there for so far.
