### ISSUE TITLE
Double request in Chrome

### ISSUE THREAD

**Issue by zachleat** [filamentgroup/loadCSS#42]
Reproduced with 250KB locally hosted stylesheet, network connection throttled in Chrome to EDGE.

![image](https://cloud.githubusercontent.com/assets/39355/6376121/9713fce2-bce1-11e4-9cc1-8640296c4744.png)

Some discussion for this took place in #41, but we this needed to be its own ticket.

**Comment by scottjehl** [comment]
devtools say that the `toggleMedia` function triggers the request, yet all that function does is switch the stylesheet's media type, and that seems like it really should not cause network activity.

Is this issue reproducible in any other browsers? Think it's maybe a Chrome bug? Seems this just started happening too... at least per my recollection.

+ @jakearchibald

**Comment by zachleat** [comment]
Well, the good news is that this is solely from the `onload` addition. Specifically, even when a callback is not specified, it was adding an empty `function() {}`. So, this issue is easily fixed on our end.

But https://github.com/filamentgroup/loadCSS/issues/41 still stands as something that is kinda broken upstream in the browser.

**Comment by zachleat** [comment]
Specifically, these are the offending commits: https://github.com/filamentgroup/loadCSS/commit/e36535a3a3e92b7a5db1723e096435770466c81c https://github.com/filamentgroup/loadCSS/commit/e36535a3a3e92b7a5db1723e096435770466c81c

*Walks away in shame.*

**Comment by zachleat** [comment]
So, after a little more research, `onload` wasn’t the only variable here.

Here is a reduced test case showing duplicate requests in Chrome 40: http://filamentgroup.github.io/loadCSS/test-chromebug.html

**Comment by scottjehl** [comment]
For what it's worth, with a fresh cache and cookie bin, this issue is not reproducible on our site: http://www.filamentgroup.com/

I wonder if it has to do with gh-pages and/or cross domain css

**Comment by zachleat** [comment]
The only variable between the php `sleep` delayed source and the static file was whether or not the resource had a valid `Last-Modified` header.

If the file had a `Last-Modified` header value that was in the past, there were no duplicate requests.
If the file did not have a `Last-Modified` header or its `Last-Modified` header value was in the future, Chrome exhibited duplicate requests.

So, yes it looks like a Chrome bug, but it does not look like a very common/problematic one.

**Comment by zachleat** [comment]
Duplicate requests (no caching headers): http://jsbin.com/zeqopa
No duplicate requests (includes caching headers): http://jsbin.com/dasiri

**Comment by zachleat** [comment]
Any complaints if I close this one @scottjehl? I feel like it’s just a little too esoteric to be worth going upstream with it?

**Comment by zachleat** [comment]
Closing.

**Comment by marcobiedermann** [comment]
Same issue on my end. I've tried your `test.html`as well as my own setup

![load-css-test](https://cloud.githubusercontent.com/assets/5244986/7169314/9decbffe-e3c4-11e4-86b7-e6b315e4f752.png)

setup:
```html
<!DOCTYPE html>
<html lang="en">
<head>

  <meta charset="UTF-8">
  <title>Website</title>

  <style>critical css…</style>

  <script>

    function loadCSS( href, before, media, callback ){…};
    loadCSS('css/style.css');

  </script>

  <noscript>
    <link href="css/style.css" rel="stylesheet">
  </noscript>

</head>
```
![load-css](https://cloud.githubusercontent.com/assets/5244986/7169315/9ded842a-e3c4-11e4-90d4-65b2ebcd90f6.png)

DevTools points to: `index.html:142`
```javascript
ref.parentNode.insertBefore( ss, ref );
```

and `index.html:161`
```javascript
ss.onloadcssdefined(function() {
    ss.media = media || "all";
  });
```
