### ISSUE TITLE
Rendering blocked in IE8 and older

### ISSUE THREAD

**Issue by zachleat** [filamentgroup/loadCSS#43]
Was doing some testing around `ownerNode` on #40 and it looks like http://filamentgroup.github.io/loadCSS/test.html does block render in IE8.

Works fine in IE9.

**Comment by zachleat** [comment]
For completeness, I think this is happening also in Android 2.3. Works fine in Android 4.

**Comment by scottjehl** [comment]
Part of me says... 'this is okay, as long as it loads the css in IE8 at all.' But I do wonder if other attribute variations might keep our async request working in all browsers while bringing IE8 in as well. For example, maybe media=print doesn't block render in IE8, or maybe adding the disabled attribute during load would help. Worth testing.

**Comment by scottjehl** [comment]
This is documented now.
