### ISSUE TITLE
Callback firing multiple times, specifically Firefox

### ISSUE THREAD

**Issue by jeromystewart** [filamentgroup/loadCSS#62]
Is this the intended behavior? I noticed that in chrome you get multiple network activity for the same stylesheet where only the last retrieves the stylesheet. I am guessing that this is intended and the "multiple tries" are how the asynchronicity is achieved.

I believe for this very same reason, firefox is calling the callback function multiple times.

Any insight?

**Comment by scottjehl** [comment]
I’ve seen this happen when the CSS file does not have future expires headers set, for caching . Is that the case for you?

**Comment by jeromystewart** [comment]
That is the case as I was using my nginx test environment when I discovered this. Great script thanks for sharing it and thank your for the response.

**Comment by scottjehl** [comment]
cool - ok to close out then? lmk if not :)

**Comment by jeromystewart** [comment]
Absolutely
