### ISSUE TITLE
[question] Browser-support

### ISSUE THREAD

**Issue by rubenswieringa** [filamentgroup/loadCSS#64]
Hey Scott,

Can you tell me what the current browser-support of this library is? I couldn't find any documentation on that.

Either way, some pretty good stuff in here!

thanks - Ruben

**Comment by melnikovkolya** [comment]
I am doing this sort of an evaluation with IE versions (only IE 11 tested so far, and works). Once complete, I will post the results here. Please remind if I forget to do it over the next 24 hours. Please share if there are any tests that you have carried out already.

**Comment by melnikovkolya** [comment]
Hi, so, I have evaluated IE vv. 6-11 and all of them supported async loading via `loadCSS`. For testing, I used a combination of VMWare and VirtualBox machines provided by modern.ie.

For versions < 9. the testing has become more difficult using tools like jsfiddle, plunker, codepen, etc., (none of them really fully support these browser versions), so I reverted to using the example provided by  @ausi in this issue thread: <https://github.com/filamentgroup/loadCSS/issues/36>

**Comment by scottjehl** [comment]
I agree it'd be good to document any known browser limitations.

Instead of using a jsfiddle or similar service, you can test the following link, which references a file that takes about 5 seconds to load. If loadCSS is working the page text will appear immediately and later change to white text on a green background:

http://filamentgroup.github.io/loadCSS/test/test.html

**Comment by mrmartineau** [comment]
Tested and working on:
* IE6
* IE7
* IE8 (so I'm guessing its fine for later versions of internet explorer)
* iOS 4.3

:smiley:

**Comment by scottjehl** [comment]
Thanks folks
Shall we update the readme with a support section and close this one out?

**Comment by mrmartineau** [comment]
yeah, good idea.
