### ISSUE TITLE
Issue with relative path including parent folder

### ISSUE THREAD

**Issue by nhoizey** [filamentgroup/loadCSS#65]
If the CSS `href` begins with `../`, [the `indexOf` test](https://github.com/filamentgroup/loadCSS/blob/master/loadCSS.js#L36) never returns true, the `media` attribute keeps the `only x` value, and the `setTimeout` goes indefinitely.

This is because the browser *translates* the relative path to an absolute one, that doesn't contain the `../` part anymore.

**Comment by nhoizey** [comment]
Ok, I just saw there's already a pull request for that: https://github.com/filamentgroup/loadCSS/pull/52

**Comment by scottjehl** [comment]
I think the proposed fix in https://github.com/filamentgroup/loadCSS/commit/1f97ab05ea1742b51f80c9cd397ff026c6e6bf3d will be a bit more reliable. Thoughts?

**Comment by nhoizey** [comment]
I think so indeed!
