### ISSUE TITLE
clarification on CSS advantages over placing css at bottom

### ISSUE THREAD

**Issue by srcspider** [filamentgroup/loadCSS#76]
Can the docs be updated to specify what's the advantage of this are over say...

```html
<!DOCTYPE html>
<meta charset="utf-8"/>
<title></title>

<style type="text/css">
/* inlined critical css styles: 
     - window dressing
     - main components
   etc */
</style>

<body>

<!-- html content from server for initial render -->

<style type="text/css">
    @import '/the/rest/of/the.css';
</style>

<script async 
    src="your/javascript.js"
></script>
```

**Comment by fatjester** [comment]
I think the advantage is this starts loading a css file without blocking the rendering of the page.
In the 'at the bottom' approach, the css wouldn't start downloading until all assets referenced in the html page have downloaded (for example, several 200kb+ images - which would delay the css loading far more than one might like).

**Comment by scottjehl** [comment]
In many modern browsers (particularly anything webkit or blink based), any CSS referenced in the page source via a `link` or `import`, no matter where it is (even at the end of the page), will cause rendering to stop as soon as the HTML parser encounters it (and not, as many expect, after the browser renders the elements that come before it in the source order). Firefox is an exception here (last I checked) - it'll render elements that precede the `link` before stopping rendering while it finishes fetching/parsing its stylesheet. Now, that's true of `link` and `import`. Here's a test page that verifies that the example above will block rendering of content that comes before it. 

http://filamentgroup.github.io/loadCSS/test/import.html

This page simply references a CSS file that takes 5 seconds to respond (we use this for all tests in the repo to test for blocking.) The gif below shows a blank screen while the css is loading, even though it comes last in the source.

![blockingimport](https://cloud.githubusercontent.com/assets/214783/8758568/1f93b646-2cab-11e5-88a0-a2c6b7f24d13.gif)

I'll add a note to the readme. Thanks

**Comment by srcspider** [comment]
Thanks @scottjehl

Are there any search engine considerations btw? I believe google removed their search preview thingy so fortunately that's no longer an issue; it was also, according to google, low usage so probably not a big deal. Not sure about other search engines.

**Comment by scottjehl** [comment]
If anything, the more assets you can safely move to async loading, the faster the page will render, and speed is now a primary factor in search engine listings. Keep your HTML content accessible to crawlers and you'll be good to go
