### ISSUE TITLE
Load multiple CSS Files

### ISSUE THREAD

**Issue by coolwebs** [filamentgroup/loadCSS#77]
Hey, fantastic piece of script here! Just used it and it worked well (even tested it in IE11). I am just curious on how I would go about loading multiple CSS files using this piece of script. Is there any documentation available to support this?

**Comment by scottjehl** [comment]
thanks. you can call `loadCSS` multiple times and the css files will be referenced in the order you called them. That said, there's no guarantees on the order they'll arrive.

**Comment by coolwebs** [comment]
Cool, thanks for letting us know. I aim to combine and minify them first so there is only one call in the function but sometimes CSS is a funny thing and there are dependancies that must be loaded first.

**Comment by rabas007** [comment]
@scottjehl - @coolwebs - 

Hi,

Any hints how this combine, minify and one function call, can be done... ? I have following code I am struggling with... 


```
< link rel = "preload"
href = "STYLE_ONE"
as = "style"
onload = "this.onload=null;this.rel='stylesheet'" >
	<
	noscript > < link rel = "stylesheet"
href = "STYLE_ONE" > < /noscript> <
	link rel = "preload"
href = "STYLE_TWO"
as = "style"
onload = "this.onload=null;this.rel='stylesheet'" >
	<
	noscript > < link rel = "stylesheet"
href = "STYLE_THREE" > < /noscript> <
	link rel = "preload"
href = "STYLE_THREE"
as = "style"
onload = "this.onload=null;this.rel='stylesheet'" >
	<
	noscript > < link rel = "stylesheet"
href = "/style.css" > < /noscript> <
	script >
	/*! loadCSS rel=preload polyfill. [c]2017 Filament Group, Inc. MIT License */
	(function () { ...
	}()); <
/script>
```
