### ISSUE TITLE
bower does not have the minified version (say loadcss.min.js ) 

### ISSUE THREAD

**Issue by akkumar** [filamentgroup/loadCSS#78]
Thanks for providing this excellent lib to load css async.

I pulled the latest version ( 0.1.7 , as of writing this ) from bower. 

It contains the 2 .js files ( the unminified ones ). 

I did this locally:  ( using https://github.com/mishoo/UglifyJS2 ) 

uglifyjs --compress -- bower_components/loadcss/onloadCSS.js bower_components/loadcss/loadCSS.js  > loadCSS.min.js

to start using the same. 

It would be nice if this is present in bower repo as well, dist as well.  Thanks, again.

**Comment by akkumar** [comment]
For now, used the minifier above to add to jsdelivr cdn. 

Issue here at: https://github.com/jsdelivr/jsdelivr/pull/5105 . 

Actual artifact available at: http://www.jsdelivr.com/#!loadcss .

**Comment by scottjehl** [comment]
Thanks for the feedback.

We're currently discussing whether or not it makes sense to continue to cater to Bower or solely maintain an NPM package, since the latter comes with better dependency management and such. This is also more of a question across all FG repos, since we love working with NPM. 

Thoughts on that are welcome

**Comment by akkumar** [comment]
@scottjehl  - I can see the dilemma (between npm vs bower ).  

My $0.02 - 

1) given this is about 2 competing build systems  (ok - not exactly ,  but close enough), I believe it will help to be published at both the places, to increase adoption of this lib. 

2) Independent of point 1 above, it would be very useful to have a minified version published as well. (should we go with only 1 or both).

**Comment by scottjehl** [comment]
I think we'll keep bower in here for those who find it useful but reserve minification to the end-developer's build. Thanks for the suggestions.

**Comment by anroots** [comment]
Being a lazy end-developer as I am, I decided to

- inline the loadCSS script with an include statement into my HTML
- minify the HTML before it's sent to the browser

If worked fine in my localhost, as I was testing with a non-minified version... but in production... as the non-minified source contains comments, it commented out the entire inlined library (and I didn't even notice).

Now, this was totally my "oops", but... :) Just saying - not all lazy front-end developers have a "minify libraries" step.
