### ISSUE TITLE
[Question] LoadCSS vs. Google Optimized CSS Delivery

### ISSUE THREAD

**Issue by pruett** [filamentgroup/loadCSS#81]
I'm curious how loadCSS stacks up against [Google's documented CSS delivery mechanism](https://developers.google.com/speed/docs/insights/OptimizeCSSDelivery).

The code in question below:

```html
<script>
      var cb = function() {
        var l = document.createElement('link'); l.rel = 'stylesheet';
        l.href = 'small.css';
        var h = document.getElementsByTagName('head')[0]; h.parentNode.insertBefore(l, h);
      };
      var raf = requestAnimationFrame || mozRequestAnimationFrame ||
          webkitRequestAnimationFrame || msRequestAnimationFrame;
      if (raf) raf(cb);
      else window.addEventListener('load', cb);
</script>
```

**Comment by scottjehl** [comment]
Depends who you ask at Google I suppose, but @jakearchibald recommends loadCSS in his latest google developers video: https://www.youtube.com/watch?v=d5_6yHixpsQ

That said, at a glance, I believe the code shown above will start the request when the first paint occurs (the first animation frame), whereas loadCSS will start the request immediately upon execution.
