### ISSUE TITLE
loadCSS sending double calls for the CSS file

### ISSUE THREAD

**Issue by chinchang** [filamentgroup/loadCSS#84]
First calls goes normally on insertBefore. But when the function sets `media` attribute to `all`, it triggers another call for the CSS file.

Why could that be happening?

Browser: Chrome 44
OS: Max OSX 10.9.2

**Comment by scottjehl** [comment]
I’ve seen this happen when you don’t have future expires headers set properly - is that possible?

**Comment by chinchang** [comment]
Indeed, that was the issue. Thanks for replying.

**Comment by superpoincare** [comment]
@bramstein I have seen this happening with Typekit. Difficult to repeat, I think it has something to do with CDN Hit/Miss too.
