### ISSUE TITLE
Does not work with rangeslider.js

### ISSUE THREAD

**Issue by jenstornell** [filamentgroup/loadCSS#96]
It worked for most part but it did not work with http://andreruffert.github.io/rangeslider.js/. I tried the callback solution but it still didn't work.

Maybe it has to do with callback fire too early, hard for me to say.

**Comment by scottjehl** [comment]
Just so I'm clear, are you trying to run this script via our onloadCSS callback function? Thanks.

**Comment by scottjehl** [comment]
Closing this out as a dupe of #74
