### ISSUE TITLE
Host on cdnjs & provide a minified version

### ISSUE THREAD

**Issue by mikeytown2** [filamentgroup/loadCSS#97]
https://github.com/cdnjs/cdnjs#adding-a-new-or-updating-an-existing-library

**Comment by superpoincare** [comment]
Why do you want it external? I think the code has to go inline for its objective to be met. 

Otherwise it is render blocking. 

And in case you load it async, you have to worry about dependency when you load your CSS with loadCSS(...).

**Comment by scottjehl** [comment]
I suppose a script can have good reason to include loadCSS for loading files later on, but yes, inlining this in `head` is the primary use case.

We have npm and bower in here because it's common to include this file via a build process and to include the latest version of the file in `head`

Does adding it to CDNs address anything these other package managers do not? Thanks

**Comment by mikeytown2** [comment]
Totally agree that hosting local is ideal. Hosting on a CDN allows for easy testing of the script before copying it locally.

Providing a loadCSS.min.js would be a nice to have.

**Comment by scottjehl** [comment]
Latest release has a minified version of all three scripts. Thanks for the push. As for CDNs, I think we're going to stick with just here and NPM as distribution options, but end users are welcome to put loadCSS on a CDN with attribution.

**Comment by mikeytown2** [comment]
If you commit the .min files then they will be available like so https://cdn.rawgit.com/filamentgroup/loadCSS/master/src/loadCSS.js

**Comment by rsteinwand** [comment]
Can we get minified versions for version 2.x? 

Possibly due to the new logic, The new rel-preload code doesn't work when minified.

**Comment by rsteinwand** [comment]
Thanks for the link.

Actually this is what I wanted: https://unpkg.com/fg-loadcss@2.0.0/dist/cssrelpreload.min.js

Same problem, IE uses a lot of CPU.

**Comment by scottjehl** [comment]
@rsteinwand glad the version you need is available now. If you have a test case for us to look at with the IE issue you mentioned, please file a new issue and we'll take a look. Thanks again.
