### ISSUE TITLE
Inserted before the first script tag or after the last stylesheet or script in the DOM?

### ISSUE THREAD

**Issue by superpoincare** [filamentgroup/loadCSS#99]
Your README.md https://github.com/filamentgroup/loadCSS/blob/master/README.md#optional-arguments says:

"By default, your stylesheet will be inserted before the first script tag in the DOM (which may be the one shown above)."

The file loadCSS.js https://github.com/filamentgroup/loadCSS/blob/master/loadCSS.js#L13 says: 

"By default, loadCSS attempts to inject the link after the last stylesheet or script in the DOM."

So which one is it?

**Comment by scottjehl** [comment]
the latter, which was a recent update. we’ll update the readme thanks!

**Comment by superpoincare** [comment]
Saw the readme update. Thanks. 

I have a basic question. The location of the default script with loadCSS( "path/to/mystylesheet.css" ) shouldn't matter right? (Since it's anyway inserted at the end)?

In my case I have inline/critical css, and an aggregated js in the end and the aggregated css loaded using loadCSS. However it seems to matter if I put this inline script on top or below the inline css (<style>...</style>).

I can see this in Chrome DevTools. With loadCSS before inline css, I see above the fold elements are using inline and the rest use the stylesheet. However if I put the loadCSS script below inline, inline styles are striked out in DevTools. 

No need to reopen the topic, as this question is slightly different than the first. 

Thanks again.

**Comment by scottjehl** [comment]
@superpoincare interesting questions. mind posting a link to the page in question?

One thing that could be happening is the script is running before later elements in source have been parsed, so the last script or style in the page happens to be the one that loadCSS is running from. 

Expected cascade is for new stylesheets to land after old ones in source order.

**Comment by superpoincare** [comment]
Hi Scott,

Here it is: www.concertedaction.com

Right now I have put the loadCSS function and loadCSS(file) on top. You can see the inline being used 

![devtool](https://cloud.githubusercontent.com/assets/13736892/10196046/634f0fe6-67ae-11e5-8b07-9d6f39b9dfb3.png)

even though one would expect the external CSS to have overwritten it. 

Probably what you say is what's happening.

**Comment by superpoincare** [comment]
Did you get a chance to look at it @scottjehl ?

**Comment by scottjehl** [comment]
not yet but I will! Btw: we're considering moving to one approach for insert location: after the last node in the body or head. https://github.com/filamentgroup/loadCSS/issues/102

But regardless, I think that this script runs early enough that we're not seeing all possible insert locations. Makes me wonder if waiting for domready or even first paint would make more sense.

**Comment by superpoincare** [comment]
I see. Something like fetch the css file(s) with media set to "only x" and use something like requestAnimationFrame to set it to "all" (with different code for old browsers)?.

**Comment by scottjehl** [comment]
Sort of. We might need to wait for something like RAF or domready before actually inserting the link in the dom.
